import { useState } from 'react';
import type { World } from '../../../shared/model/world';
import type { Command } from '../../../shared/model/commands';
import type { Army, UnitType } from '../domain/types';
import type { Settlement } from '../../city/domain/types';
import { UNIT_TYPES } from '../domain/units';
import { armyOverview, recruitmentPlan, UNIT_ROLES, count, percent } from '../domain/commandRoom';
import { Icon } from '../../../shared/ui/Icons';
import { Cost } from '../../../shared/ui/Shared';
import { clock } from '../../../shared/time/clock';

export function RecruitmentPanel({ world, army, city, run, busy, now, onCity, onOpenCity, onLogistics }: { world: World; army: Army; city: Settlement; run: (c: Command, message?: string) => void; busy: boolean; now: number; onCity?: (id: number) => void; onOpenCity?: (id: number) => void; onLogistics: () => void }) {
    const [type, setType] = useState<UnitType>('infantry'), [quantity, setQuantity] = useState(20);
    const overview = armyOverview(world, army, now), plan = recruitmentPlan(world, army, city, type, quantity, now), meta = UNIT_ROLES[type];
    const cities = world.settlements.filter(s => s.owner_id === army.owner_id);
    const changeQuantity = (n: number) => setQuantity(Math.max(1, Math.min(200, Math.floor(n || 1))));
    return <div className="army-recruit-layout"><div className="army-composition"><section className="command-panel"><div className="command-section-heading"><div><span className="command-kicker">The soldiers under your banner</span><h2>Army composition</h2></div><span className="command-pill">{count(overview.total)} / 1,000</span></div>
        <div className="command-unit-cards">{UNIT_TYPES.map(key => <button key={key} className={`command-unit-card unit-${key}`} aria-pressed={type === key} onClick={() => setType(key)}><div className="unit-card-banner"><Icon name={UNIT_ROLES[key].icon} size={38}/><span>{UNIT_ROLES[key].role}</span></div><strong>{count(army[key])}</strong><h3>{UNIT_ROLES[key].name}</h3><div className="command-meter"><i style={{ width: `${overview.total ? army[key] / overview.total * 100 : 0}%` }}/></div><small>{overview.total ? percent(army[key] / overview.total) : '0%'} of your army</small><span className="unit-card-select">{type === key ? 'Selected for recruiting' : 'Recruit this unit'}<Icon name="plus" size={14}/></span></button>)}</div>
        <div className="army-capacity-line"><span>{count(overview.free)} spaces available</span><span>{overview.queued ? `${overview.queued} soldiers in training` : 'Select a unit to recruit'}</span></div>
        {overview.total === 0 && <div className="command-note"><Icon name="flag"/><p>A commander needs soldiers. Recruit here or bring in troops from another army.</p><button className="command-text-button" onClick={onLogistics}>Transfer troops<Icon name="arrow" size={15}/></button></div>}
    </section><section className="command-panel command-training"><div className="command-section-heading"><div><span className="command-kicker">Reinforcements on the way</span><h2>Training queue</h2></div><span className="command-pill">{plan.orders.length} / 3 slots</span></div>
        {plan.orders.length ? <ol className="command-queue-list">{plan.orders.map((order, index) => { const waiting = now < Date.parse(order.started_at), progress = Math.min(100, Math.max(0, (now - Date.parse(order.started_at)) / Math.max(1, Date.parse(order.finish_at) - Date.parse(order.started_at)) * 100)); const origin = world.settlements.find(s => s.id === order.settlement_id); return <li key={order.id}><span className="queue-number">{index + 1}</span><Icon name={UNIT_ROLES[order.item as UnitType]?.icon ?? 'army'}/><div><strong>{order.quantity} {UNIT_ROLES[order.item as UnitType]?.name.toLowerCase() ?? order.item}</strong><small>{waiting ? 'Queued' : 'Training'}{origin ? ` in ${origin.name}` : ''} · Ready in {clock(Math.max(0, (Date.parse(order.finish_at) - now) / 1000))}</small><div className="command-meter"><i style={{ width: `${progress}%` }}/></div></div></li>; })}</ol> : <div className="command-queue-empty"><Icon name="time"/><p>No troops in training.<small>Add a batch from the recruitment panel.</small></p></div>}
        <small className="command-muted">This army stays in place until all training is complete.</small>
    </section></div>
    <section className="command-panel command-recruit-form"><div className="command-section-heading"><div><span className="command-kicker">Add to this army</span><h2>Recruit {meta.name.toLowerCase()}</h2></div><Icon name={meta.icon} size={27}/></div><p className="command-muted">{meta.detail}</p>
        <label className="command-label">Training city<select aria-label="Training city" value={city.id} onChange={event => onCity?.(Number(event.target.value))}>{cities.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
        <div className="recruit-site-status"><span className={plan.near ? 'available' : ''}><Icon name={plan.near ? 'check' : 'flag'} size={14}/>{plan.near ? 'Army is here' : army.status === 'moving' ? 'Army is marching' : 'Army is elsewhere'}</span><span>{plan.level ? `${plan.building === 'stables' ? 'Stables' : 'Barracks'} Lv. ${plan.level}` : `${plan.building === 'stables' ? 'Stables' : 'Barracks'} required`}</span></div>
        <label className="command-label" htmlFor="recruit-quantity">Soldiers to train</label><div className="command-quantity"><button aria-label="Train fewer soldiers" onClick={() => changeQuantity(quantity - 5)}>−</button><input id="recruit-quantity" type="number" min={1} max={200} value={quantity} onChange={event => changeQuantity(Number(event.target.value))}/><button aria-label="Train more soldiers" onClick={() => changeQuantity(quantity + 5)}>+</button></div><div className="recruit-presets">{[10, 25, 50].map(n => <button key={n} aria-pressed={quantity === n} onClick={() => changeQuantity(n)}>{n}</button>)}<button disabled={!plan.max} onClick={() => changeQuantity(plan.max)}>Max {plan.max}</button></div>
        <div className="recruit-cost-heading"><span>Total supplies</span><small>From {city.name}</small></div><Cost cost={plan.cost} resources={plan.resources} compact/>
        <div className="recruit-timing"><span>Training time<b>{clock(plan.seconds)}</b></span><span>Ready in, with queue<b>{clock(plan.finishSeconds)}</b></span></div>
        <button className="command-button primary" disabled={busy || !!plan.reason} onClick={() => run({ type: 'recruit', armyId: army.id, settlementId: city.id, item: type, quantity }, `${quantity} ${meta.name.toLowerCase()} added to ${army.name}’s training`)}>Train {quantity} {meta.name.toLowerCase()}<Icon name="plus" size={16}/></button>
        {plan.reason && <div className="recruit-blocked"><p>{plan.reason}</p>{!plan.near && !plan.orders.length && <button className="command-text-button" disabled={busy} onClick={() => run({ type: 'move', armyId: army.id, settlementId: city.id, x: city.x + 40, y: city.y + 30 }, `${army.name} is marching to ${city.name}`)}>March to {city.name}<Icon name="arrow" size={15}/></button>}{!plan.level && onOpenCity && <button className="command-text-button" onClick={() => onOpenCity(city.id)}>Develop this city<Icon name="arrow" size={15}/></button>}</div>}
    </section></div>;
}
