import { BATTLE_TERRAINS } from '../src/features/battle/domain/terrain';
import type { Terrain } from '../src/features/battle/domain/types';
import { FIELD_W,FIELD_H } from '../src/features/battle/domain/dimensions';
import test from 'node:test';
import assert from 'node:assert/strict';
import { createSolo } from '../src/features/campaign/domain/newRealm';
import { newBattle } from '../src/features/battle/domain/creation';
import { stepBattle } from '../src/features/battle/domain/simulation';
import { chooseAI } from '../src/features/battle/domain/ai';
import { moveFormations } from '../src/features/battle/domain/movement';
import { autoRally } from '../src/features/battle/domain/morale';
import { chooseAutomaticSpell } from '../src/features/magic/domain/automatic';
import { SPELLS } from '../src/features/magic/domain/spells';
import { commandBattle } from '../src/features/battle/domain/commands';
const setup=(troops={infantry:120,archers:60,cavalry:24},terrain:Terrain='plains')=>{const w=createSolo('Rex');return newBattle(1,'own',{...w.armies[0],...troops},troops,terrain,'normal','Enemy');};
test('all battles start automatically and AI orders both owned armies',()=>{const {battle:b,formations:fs}=setup();assert.equal(b.phase,'combat');fs.filter(f=>f.side==='defender').forEach(f=>f.owner_id='rival');stepBattle(b,fs,.1);assert.ok(fs.every(f=>f.target_formation_id));assert.ok(fs.some(f=>f.owner_id==='own'&&f.status==='moving'));assert.ok(fs.some(f=>f.owner_id==='rival'&&f.status==='moving'));});
test('no elapsed time cannot cause a hit or advance combat',()=>{const {battle:b,formations:fs}=setup();const before=JSON.stringify(fs);stepBattle(b,fs,0);assert.equal(b.elapsed,0);assert.equal(JSON.stringify(fs),before);});
test('stable valid targets survive small position changes',()=>{const {battle:b,formations:fs}=setup();chooseAI(b,fs);const targets=fs.map(f=>f.target_formation_id);fs.forEach(f=>f.y+=.1);chooseAI(b,fs);assert.deepEqual(fs.map(f=>f.target_formation_id),targets);});
test('movement uses a common snapshot regardless of iteration order',()=>{const {battle:b,formations:fs}=setup();chooseAI(b,fs);const reverse=structuredClone(fs).reverse();moveFormations(b,fs,new Map(fs.map(f=>[f.id,f])),.05);moveFormations(b,reverse,new Map(reverse.map(f=>[f.id,f])),.05);for(const f of fs){const g=reverse.find(g=>g.id===f.id)!;assert.ok(Math.abs(f.x-g.x)<1e-10);assert.ok(Math.abs(f.y-g.y)<1e-10);}});
test('an engaged regiment turns toward its opponent',()=>{const {battle:b,formations:fs}=setup({infantry:60,archers:0,cavalry:0});fs[0].x=570;fs[1].x=630;fs[0].facing=90;chooseAI(b,fs);moveFormations(b,fs,new Map(fs.map(f=>[f.id,f])),.1);assert.ok(fs[0].facing<90);});
test('overlapping allies separate instead of stacking forever',()=>{const {battle:b,formations:fs}=setup();const a=fs[0],c=fs[1];c.x=a.x;c.y=a.y;chooseAI(b,fs);for(let i=0;i<15;i++)moveFormations(b,fs,new Map(fs.map(f=>[f.id,f])),.1);assert.ok(Math.hypot(a.x-c.x,a.y-c.y)>25);});
test('rallies trigger once per side without player input',()=>{const {battle:b,formations:fs}=setup();fs.forEach(f=>f.morale=30);autoRally(b,fs);assert.equal(b.rally_attacker,true);assert.equal(b.rally_defender,true);assert.ok(fs.every(f=>f.morale===55));autoRally(b,fs);assert.ok(fs.every(f=>f.morale===55));});
test('AI does not waste healing on a full formation and respects mana',()=>{const {battle:b,formations:fs}=setup();const heal=SPELLS.filter(s=>s.id==='mend');assert.equal(chooseAutomaticSpell(b,fs,'attacker',heal,50),undefined);const f=fs.find(f=>f.side==='attacker')!;f.soldiers-=20;assert.equal(chooseAutomaticSpell(b,fs,'attacker',heal,4),undefined);assert.equal(chooseAutomaticSpell(b,fs,'attacker',heal,5)?.target,f.id);});
test('automatic battles reject manual movement and rally commands',()=>{const {battle:b,formations:fs}=setup();const ctx={active:b,world:{formations:fs},playerId:'own'} as any;assert.throws(()=>commandBattle(ctx,{type:'order',battleId:1,order:{kind:'move',ids:[fs[0].id],x:500,y:300}}),/automatically/);assert.throws(()=>commandBattle(ctx,{type:'rally',battleId:1}),/automatically/);});
for(const terrain of BATTLE_TERRAINS)test(`AI completes ${terrain} combat with bounded positions and conserved casualties`,()=>{const {battle:b,formations:fs}=setup(undefined,terrain);for(let i=0;i<9005&&b.status==='active';i++){stepBattle(b,fs,.1);assert.ok(fs.every(f=>Number.isFinite(f.x)&&Number.isFinite(f.y)&&f.x>=12&&f.x<=FIELD_W-12&&f.y>=30&&f.y<=FIELD_H-30&&f.soldiers>=0&&f.soldiers<=f.initial_soldiers));}assert.equal(b.status,'resolved');assert.ok(b.elapsed<900,'Combat should resolve before the fallback timer');assert.equal(b.result!.attacker_losses+b.result!.attacker_survivors,b.result!.attacker_initial);assert.equal(b.result!.defender_losses+b.result!.defender_survivors,b.result!.defender_initial);});
