import test from 'node:test';import assert from 'node:assert/strict';import {Box3,Mesh} from 'three';
import {FACTIONS,factionOf,type Faction} from '../src/features/factions/domain/factions';
import {changeFaction,debugCity} from '../src/features/factions/domain/debug';
import {createSolo} from '../src/features/campaign/domain/newRealm';import type {LocalCommandContext} from '../src/shared/model/commands';
import {validateSave} from '../src/platform/storage/saves';import {queueSlot} from '../src/features/city/domain/slotCommands';
import {createBuildingModel} from '../src/features/city/rendering/three/buildingModels';import {createSlotModel} from '../src/features/city/rendering/three/slotModels';
import {createCityWalls} from '../src/features/city/rendering/three/cityWalls';import {createCityLandscape} from '../src/features/city/rendering/three/landscape';
import {disposeCityObject} from '../src/features/city/rendering/three/modelKit';
function fixture(){const world=createSolo('Builder');const context:LocalCommandContext={world,playerId:world.players[0].id,nextId:()=>123,active:undefined,now:world.server_now,paused:()=>{},finalize:()=>{}};return {world,context};}
test('eleven factions persist in solo saves, legacy saves default to Roman, and invalid factions are rejected',()=>{assert.equal(Object.keys(FACTIONS).length,11);const f=fixture();assert.equal(factionOf(f.world.settlements[0].faction),'roman');for(const faction of Object.keys(FACTIONS) as Faction[]){changeFaction(f.context,{type:'setFaction',faction});assert.equal(validateSave(f.world).settlements[0].faction,faction);}assert.throws(()=>changeFaction(f.context,{type:'setFaction',faction:'bad' as Faction}));const bad=structuredClone(f.world);bad.settlements[0].faction='bad' as Faction;assert.throws(()=>validateSave(bad));});
test('debug resources respect separate capacities, completion is immediate, and demolition cancels pending work',()=>{const f=fixture(),town=f.world.settlements[0];debugCity(f.context,{type:'debugCity',action:'resources',value:0});assert.equal(town.gold,5000);queueSlot(f.context,{type:'buildSlot',slot:0,item:'warehouse'});debugCity(f.context,{type:'debugCity',action:'finish'});assert.equal(f.world.city_slots![0].level,1);assert.equal(f.world.orders.length,0);assert.equal(town.capacity,7500);debugCity(f.context,{type:'debugCity',action:'resources',value:0});assert.equal(town.gold,7500);assert.equal(town.food,5000);queueSlot(f.context,{type:'upgradeSlot',slot:0});debugCity(f.context,{type:'debugCity',action:'demolish',target:'slot:0'});assert.equal(f.world.city_slots!.length,0);assert.equal(f.world.orders.length,0);assert.equal(town.capacity,5000);assert.equal(town.gold,5000);assert.doesNotThrow(()=>validateSave(f.world));});
test('shrinking the city clears only unsupported plots, their orders and lost tower research; river site survives',()=>{const f=fixture();f.world.buildings.find(b=>b.building_type==='market')!.level=5;f.world.city_slots=[{settlement_id:1,slot_index:0,building_type:'warehouse',level:1},{settlement_id:1,slot_index:15,building_type:'mage_tower',level:10},{settlement_id:1,slot_index:16,building_type:'fishery',level:2}];f.world.spell_research=[{settlement_id:1,spell_id:'spark',researched_at:f.context.now}];debugCity(f.context,{type:'debugCity',action:'demolish',target:'market'});assert.deepEqual(f.world.city_slots!.map(s=>s.slot_index),[0,16]);assert.equal(f.world.spell_research.length,0);assert.equal(f.world.settlements[0].food_gross_rate,34);assert.doesNotThrow(()=>validateSave(f.world));});
test('debug limits, permissions and invalid targets reject changes; tower supports level ten',()=>{const f=fixture();f.world.city_slots=[{settlement_id:1,slot_index:2,building_type:'mage_tower',level:1}];debugCity(f.context,{type:'debugCity',action:'level',target:'slot:2',value:10});assert.equal(f.world.city_slots[0].level,10);for(const cmd of [{type:'debugCity',action:'level',target:'market',value:6},{type:'debugCity',action:'level',target:'slot:2',value:11},{type:'debugCity',action:'demolish',target:'slot:5'},{type:'debugCity',action:'resources',value:-100}] as const){const before=structuredClone(f.world);assert.throws(()=>debugCity(f.context,cmd));assert.deepEqual(f.world,before);}f.world.debug_enabled=false;assert.throws(()=>debugCity(f.context,{type:'debugCity',action:'resources',value:0}),/disabled/);f.world.debug_enabled=true;f.context.active={status:'active'} as any;assert.throws(()=>debugCity(f.context,{type:'debugCity',action:'demolish',target:'market'}),/battle/);});
test('all faction models have finite geometry and distinct main halls through five levels, plus ten mage stages',()=>{const signatures=new Set<string>();for(const faction of Object.keys(FACTIONS) as Faction[]){let signature='';for(let level=1;level<=5;level++){const model=createBuildingModel('market',level,faction);let vertices=0;model.traverse(o=>{if(o instanceof Mesh){const points=o.geometry.getAttribute('position');vertices+=points.count;for(const n of points.array)assert.ok(Number.isFinite(n));}});signature+=vertices+',';const bounds=new Box3().setFromObject(model);assert.ok(bounds.max.x-bounds.min.x<4.5,faction);disposeCityObject(model);}signatures.add(signature);for(const type of ['barracks','stables','warehouse','granary','smithy','fishery','mage_tower','housing'] as const){const model=createSlotModel(type,type==='mage_tower'?10:5,faction);const bounds=new Box3().setFromObject(model);assert.ok(bounds.max.y>0);assert.ok(bounds.max.x-bounds.min.x<4.5,`${faction} ${type}`);disposeCityObject(model);}for(const model of [createCityWalls(5,5,faction),createCityLandscape(5,faction)]){assert.ok(new Box3().setFromObject(model).max.y>0);disposeCityObject(model);}}assert.equal(signatures.size,11,'Architecture must differ, not just material colors');});
test('city faction selector and debug controls render all cultures and remain separate from the server cheat flag',async()=>{const React=await import('react');(globalThis as any).React=React;const {createElement}=React,{renderToStaticMarkup}=await import('react-dom/server'),{CityDebugPanel}=await import('../src/features/factions/ui/CityDebugPanel');const f=fixture();const props={world:f.world,owner:f.context.playerId,target:'market',name:'Main building',level:0,max:5,busy:false,run:()=>{}};let html=renderToStaticMarkup(createElement(CityDebugPanel,props));assert.equal((html.match(/<option/g)??[]).length,17);for(const label of ['Fill storage','Finish construction','Demolish Main building','+1,000 resources'])assert.ok(html.includes(label));f.world.debug_enabled=false;html=renderToStaticMarkup(createElement(CityDebugPanel,props));assert.equal((html.match(/<option/g)??[]).length,11);assert.ok(!html.includes('Fill storage'));});
