import {PGlite} from '@electric-sql/pglite';import {readFile} from 'node:fs/promises';import assert from 'node:assert/strict';
import {SPELLS} from '../src/features/magic/domain/spells.ts';
const db=new PGlite(),u='11111111-1111-4111-8111-111111111111',v='22222222-2222-4222-8222-222222222222';
const login=async(id=u)=>db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${id}',false);`),admin=async(sql)=>{await db.exec('reset role');return db.exec(sql);},rpc=async(name,args=[])=>db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as result`,args),snap=async()=> (await rpc('peris_snapshot')).rows[0].result;
const finish=async()=>{await admin(`update public.peris_orders set started_at=now()-interval '30 seconds',finish_at=now()-interval '1 second' where owner_id='${u}' and kind='upgrade'`);await login();await rpc('sync_my_state');};
try{
 await db.exec(`create schema auth;create table auth.users(id uuid primary key);create role anon;create role authenticated;create role service_role;create function auth.uid()returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated,anon;grant execute on function auth.uid()to authenticated,anon;create publication supabase_realtime;`);
 await db.exec(await readFile('supabase/FRESH_INSTALL_V8.sql','utf8'));const migration=await readFile('supabase/UPGRADE_MAGE_TOWER.sql','utf8');await db.exec(migration);await db.exec(migration);
 await db.exec(`insert into auth.users values('${u}'),('${v}');`);await login();await rpc('create_player',['Wizard']);let w=await snap();const sid=w.settlements[0].id;
 await assert.rejects(()=>rpc('peris_research_spell',['spark']),/mage tower/);
 await admin(`insert into public.peris_city_slots values(${sid},0,'warehouse',5),(${sid},1,'granary',5),(${sid},2,'warehouse',5);select public.peris_city_economy(${sid});update public.settlements set wood=30000,stone=30000,food=17500,gold=30000 where id=${sid};`);await login();await rpc('peris_queue_slot',[5,'mage_tower']);await finish();await assert.rejects(()=>rpc('peris_queue_slot',[4,'mage_tower']),/Only one/);
 await assert.rejects(()=>rpc('peris_research_spell',['inferno']),/level 10/);await rpc('peris_research_spell',['spark']);const gold=(await snap()).settlements[0].gold;await assert.rejects(()=>rpc('peris_research_spell',['spark']),/already/);assert.equal((await snap()).settlements[0].gold,gold);
 for(let level=2;level<=10;level++){await rpc('peris_queue_slot',[5,null]);await finish();assert.equal((await snap()).city_slots.find(s=>s.building_type==='mage_tower').level,level);}
 await assert.rejects(()=>rpc('peris_queue_slot',[5,null]),/Maximum/);
 const catalog=(await db.query('select * from public.peris_spell_catalog order by level,id')).rows;assert.equal(catalog.length,20);for(const spell of SPELLS){const dbSpell=catalog.find(s=>s.id===spell.id);for(const [key,value] of Object.entries(spell).filter(([key])=>key!=='description'))assert.equal(typeof value==='number'?Number(dbSpell[key]):dbSpell[key],value,`${spell.id}.${key}`);}for(let l=1;l<=10;l++)assert.equal(catalog.filter(s=>s.level===l).length,2);for(const s of catalog.filter(s=>s.id!=='spark'))await rpc('peris_research_spell',[s.id]);assert.equal((await snap()).spell_research.length,20);
 await rpc('peris_raid',[1]);await admin(`update public.armies set arrival_at=now()-interval '1 second' where owner_id='${u}'`);await login();await rpc('sync_my_state');w=await snap();const bid=w.battles[0].id,own=w.formations.find(f=>f.owner_id===u),enemy=w.formations.find(f=>f.owner_id!==u);
 await assert.rejects(()=>rpc('peris_cast_spell',[bid,'spark',enemy.id]),/combat/);await rpc('peris_ready',[bid]);
 await admin(`update public.battles set last_tick_at=now() where id=${bid};`);await login();const troops=(await snap()).formations.find(f=>f.id===enemy.id).soldiers;await assert.rejects(()=>rpc('peris_cast_spell',[bid,'spark',own.id]),/correct side/);await rpc('peris_cast_spell',[bid,'spark',enemy.id]);w=await snap();assert.equal(w.formations.find(f=>f.id===enemy.id).soldiers,troops-8);assert.equal(w.battles[0].mana_attacker,115);await assert.rejects(()=>rpc('peris_cast_spell',[bid,'spark',enemy.id]),/recovering/);
 await admin(`update public.battles set elapsed=10,last_tick_at=now() where id=${bid};update public.battle_formations set soldiers=0,status='routed',morale=0 where id=${own.id};`);await login();await rpc('peris_cast_spell',[bid,'resurrection',own.id]);w=await snap();assert.equal(w.formations.find(f=>f.id===own.id).soldiers,25);assert.equal(w.formations.find(f=>f.id===own.id).status,'idle');assert.equal(w.battles[0].mana_attacker,85);
 for(const spell of catalog){
  await admin(`update public.battles set elapsed=100,spell_ready_attacker=0,mana_attacker=120,last_tick_at=now() where id=${bid};update public.battle_formations set initial_soldiers=100,soldiers=80,morale=50,stamina=40,status='idle',magic_attack=1,magic_defence=0,magic_speed=1 where battle_id=${bid}`);await login();
  const before=(await snap()).formations;await rpc('peris_cast_spell',[bid,spell.id,spell.target.startsWith('ally')||spell.target==='allies'?own.id:enemy.id]);const after=await snap();
  assert.notDeepEqual(after.formations,before,spell.name);assert.equal(after.battles[0].mana_attacker,120-spell.mana);
 }
 await assert.rejects(()=>db.exec(`insert into public.peris_spell_research values(${sid},'spark',now())`),/permission denied/);await assert.rejects(()=>db.exec(`update public.peris_spell_catalog set damage=1000`),/permission denied/);
 await login(v);await rpc('create_player',['Other']);assert.equal((await db.query(`select count(*) as n from public.peris_spell_research where settlement_id=${sid}`)).rows[0].n,0);await assert.rejects(()=>rpc('peris_cast_spell',[bid,'inferno',enemy.id]),/Not your battle/);
 console.log('PASS · shared-world unique tower, levels 1–10, twenty research spells, casting effects, target ownership, mana, cooldown, resurrection, migration reruns and access controls');
}catch(e){console.error(e.message,e.where??'');process.exitCode=1;}finally{await db.close();}
