import test from 'node:test';import assert from 'node:assert/strict';
import {createSolo} from '../src/features/campaign/domain/newRealm';
import {queueSlot} from '../src/features/city/domain/slotCommands';
import {settleLocal} from '../src/features/campaign/domain/settlement';
import {SPELLS,researchCost,maximumMana} from '../src/features/magic/domain/spells';
import {researchSpell,castSpell} from '../src/features/magic/domain/commands';
import {newBattle} from '../src/features/battle/domain/creation';
import type {LocalCommandContext} from '../src/shared/model/commands';
import {validateSave} from '../src/platform/storage/saves';
function fixture(){const world=createSolo('Wizard');const context:LocalCommandContext={world,playerId:world.players[0].id,nextId:()=>123,active:undefined,now:world.server_now,paused:()=>{},finalize:()=>{}};return {world,context};}
function battleFixture(){const f=fixture();f.world.city_slots=[{settlement_id:1,slot_index:0,building_type:'mage_tower',level:10}];f.world.spell_research=SPELLS.map(s=>({settlement_id:1,spell_id:s.id,researched_at:f.context.now}));const instance=newBattle(1,f.context.playerId,f.world.armies[0],{infantry:200,archers:80,cavalry:24},'plains','normal','Enemy');instance.battle.phase='combat';f.world.battles=[instance.battle];f.world.formations=instance.formations;f.context.active=instance.battle;return f;}
test('unique optional tower can occupy any city plot, grows through ten levels and rejects a second pending tower',()=>{const f=fixture();f.world.city_slots=[{settlement_id:1,slot_index:0,building_type:'warehouse',level:5},{settlement_id:1,slot_index:1,building_type:'warehouse',level:5},{settlement_id:1,slot_index:2,building_type:'granary',level:5}];Object.assign(f.world.settlements[0],{wood:30000,stone:30000,food:17500,gold:30000,capacity:30000,food_capacity:17500});queueSlot(f.context,{type:'buildSlot',slot:5,item:'mage_tower'});assert.equal(f.world.city_slots[3].level,0);for(let level=1;level<=10;level++){settleLocal(f.world,f.context.playerId,Date.parse(f.world.orders[0].finish_at));assert.equal(f.world.city_slots[3].level,level);f.context.now=f.world.server_now=new Date(Date.parse(f.context.now)+200000).toISOString();if(level<10){assert.throws(()=>queueSlot(f.context,{type:'buildSlot',slot:4,item:'mage_tower'}),/Only one/);queueSlot(f.context,{type:'upgradeSlot',slot:5});}}const before=structuredClone(f.world);assert.throws(()=>queueSlot(f.context,{type:'upgradeSlot',slot:5}),/Maximum/);assert.deepEqual(f.world,before);});
test('two spells per level, research gates and duplicate fees, and optional-save migration',()=>{assert.equal(SPELLS.length,20);assert.equal(new Set(SPELLS.map(s=>s.id)).size,20);for(let i=1;i<=10;i++)assert.equal(SPELLS.filter(s=>s.level===i).length,2);const f=fixture();assert.throws(()=>researchSpell(f.context,{type:'researchSpell',spell:'spark'}),/level 1/);f.world.city_slots=[{settlement_id:1,slot_index:2,building_type:'mage_tower',level:1}];assert.throws(()=>researchSpell(f.context,{type:'researchSpell',spell:'inferno'}),/level 10/);const before=f.world.settlements[0].gold;researchSpell(f.context,{type:'researchSpell',spell:'spark'});assert.equal(f.world.settlements[0].gold,before-researchCost(SPELLS[0]).gold);const gold=f.world.settlements[0].gold;assert.throws(()=>researchSpell(f.context,{type:'researchSpell',spell:'spark'}),/already/);assert.equal(f.world.settlements[0].gold,gold);assert.deepEqual(validateSave(f.world).spell_research,f.world.spell_research);const invalid=structuredClone(f.world);invalid.city_slots!.push({...invalid.city_slots![0],slot_index:3});assert.throws(()=>validateSave(invalid));});
test('all twenty spells produce their described effects without exceeding original troop numbers',()=>{for(const spell of SPELLS){const f=battleFixture(),own=f.world.formations.filter(s=>s.owner_id===f.context.playerId),enemy=f.world.formations.filter(s=>s.owner_id!==f.context.playerId);for(const s of own){s.soldiers=Math.max(1,s.soldiers-20);s.morale=50;s.stamina=40;}for(const s of enemy){s.stamina=50;s.morale=60;}const target=(spell.target==='ally'||spell.target==='allies'?own:enemy)[0],before=structuredClone(f.world.formations);castSpell(f.context,{type:'castSpell',battleId:1,spell:spell.id,target:target.id});assert.equal(f.context.active!.mana_attacker,maximumMana(10)-spell.mana);assert.equal(f.context.active!.spell_ready_attacker,8);assert.notDeepEqual(f.world.formations,before,spell.name);assert.ok(f.world.formations.every(s=>s.soldiers>=0&&s.soldiers<=s.initial_soldiers));if(spell.damage)assert.ok(target.soldiers<before.find(s=>s.id===target.id)!.soldiers,spell.name);if(spell.attack)assert.equal(target.magic_attack,1+spell.attack);if(spell.defence)assert.equal(target.magic_defence,spell.defence);if(spell.speed)assert.equal(target.magic_speed,1+spell.speed);}});
test('mana, cooldown, target side and research are enforced atomically; resurrection recovers a fallen formation',()=>{const f=battleFixture(),b=f.context.active!,own=f.world.formations.find(s=>s.owner_id===f.context.playerId)!,enemy=f.world.formations.find(s=>s.owner_id!==f.context.playerId)!;const before=structuredClone(f.world);assert.throws(()=>castSpell(f.context,{type:'castSpell',battleId:1,spell:'spark',target:own.id}),/enemy/);assert.deepEqual(f.world,before);castSpell(f.context,{type:'castSpell',battleId:1,spell:'spark',target:enemy.id});assert.throws(()=>castSpell(f.context,{type:'castSpell',battleId:1,spell:'spark',target:enemy.id}),/recovering/);b.elapsed=8;b.mana_attacker=0;assert.throws(()=>castSpell(f.context,{type:'castSpell',battleId:1,spell:'spark',target:enemy.id}),/mana/);b.mana_attacker=120;own.soldiers=0;own.status='routed';own.morale=0;castSpell(f.context,{type:'castSpell',battleId:1,spell:'resurrection',target:own.id});assert.equal(own.soldiers,25);assert.equal(own.status,'idle');assert.equal(own.morale,65);b.elapsed=16;f.world.spell_research=[];assert.throws(()=>castSpell(f.context,{type:'castSpell',battleId:1,spell:'spark',target:enemy.id}),/Research/);});
test('mage tower has ten distinct silhouettes, including levels above five',async()=>{const {createMageTower}=await import('../src/features/city/rendering/three/mageTower'),{disposeCityObject}=await import('../src/features/city/rendering/three/modelKit'),{Box3}=await import('three');let height=0;const counts=new Set<number>();for(let level=1;level<=10;level++){const model=createMageTower(level),size=new Box3().setFromObject(model);assert.ok(size.max.y>height);height=size.max.y;let vertices=0;model.traverse((node:any)=>{vertices+=node.geometry?.attributes.position.count??0;});counts.add(vertices);disposeCityObject(model);}assert.equal(counts.size,10);});
test('spell victory finalizes the battle once and magical protection reduces incoming spells',()=>{const f=battleFixture(),b=f.context.active!,enemy=f.world.formations.filter(s=>s.side==='defender');const first=enemy[0];first.magic_defence=.4;const troops=first.soldiers;castSpell(f.context,{type:'castSpell',battleId:1,spell:'spark',target:first.id});assert.equal(first.soldiers,troops-Math.ceil(8*.6));b.elapsed=8;let finalized=0;f.context.finalize=()=>finalized++;for(const s of enemy)s.soldiers=1;castSpell(f.context,{type:'castSpell',battleId:1,spell:'inferno'});assert.equal(b.status,'resolved');assert.equal(b.winner_side,'attacker');assert.equal(finalized,1);assert.throws(()=>castSpell(f.context,{type:'castSpell',battleId:1,spell:'inferno'}),/combat/);assert.equal(finalized,1);});
