import {PGlite} from '@electric-sql/pglite';import {readFile} from 'node:fs/promises';import assert from 'node:assert/strict';
import {createSolo} from '../src/features/campaign/domain/newRealm.ts';import {refreshCityEconomy} from '../src/features/city/domain/slots.ts';import {advancePopulationEconomy,populationRates} from '../src/features/city/domain/population.ts';
const db=new PGlite(),u='11111111-1111-4111-8111-111111111111',v='22222222-2222-4222-8222-222222222222';
const login=async(id=u)=>db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${id}',false);`),rpc=async(name,args=[])=>db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as result`,args),snap=async()=> (await rpc('peris_snapshot')).rows[0].result;
try{
 await db.exec(`create schema auth;create table auth.users(id uuid primary key);create role anon;create role authenticated;create role service_role;create function auth.uid()returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated,anon;grant execute on function auth.uid()to authenticated,anon;create publication supabase_realtime;`);
 await db.exec(await readFile('supabase/FRESH_INSTALL_V8.sql','utf8'));await db.exec(`insert into auth.users values('${u}'),('${v}');`);await login();await rpc('create_player',['Rex']);let w=await snap();const sid=w.settlements[0].id;assert.equal(w.settlements[0].population,30);assert.equal(w.settlements[0].population_capacity,40);assert.equal(w.settlements[0].food_rate,14.4);
 await rpc('peris_queue_slot',[0,'housing']);assert.equal((await snap()).settlements[0].population_capacity,40);await rpc('peris_debug_city',['finish']);w=await snap();assert.equal(w.settlements[0].population_capacity,70);assert.equal(w.city_slots[0].level,1);await rpc('peris_queue_slot',[1,'housing']);await rpc('peris_debug_city',['finish']);assert.equal((await snap()).settlements[0].population_capacity,100);
 await rpc('peris_debug_city',['level','slot:0',5]);await rpc('peris_debug_city',['population',null,0]);assert.equal((await snap()).settlements[0].population,220);await rpc('peris_debug_city',['demolish','slot:0']);assert.equal((await snap()).settlements[0].population,70);
 await assert.rejects(()=>rpc('peris_population_accrue',[sid,new Date().toISOString()]),/permission/);await assert.rejects(()=>rpc('peris_population_event',[0,1,0,10,10]),/permission/);
 await db.exec('reset role');const migration=await readFile('supabase/UPGRADE_HOUSING_AND_POPULATION.sql','utf8');await db.exec(migration);await db.exec(migration);
 // Compare exact client/server integration across high/low staffing, full stores and famine.
 const keys=['population','population_capacity','workers_required','wood_bonus','stone_bonus','food_bonus','gold_bonus','wood','stone','food','gold','capacity','food_capacity','resources_updated_at'];
 for(let seed=1;seed<=40;seed++){
  const world=createSolo('Parity');world.buildings.forEach(b=>b.level=seed%6);world.city_slots=[{settlement_id:1,slot_index:0,building_type:'housing',level:seed%5+1},{settlement_id:1,slot_index:16,building_type:'fishery',level:seed%6}];refreshCityEconomy(world,1);const town=world.settlements[0];town.population=10+(seed*37)%(town.population_capacity-10);town.food=seed%4===0?0:seed%4===1?5000:seed%4===2?.2:20;town.resources_updated_at='2026-10-07T00:00:00.000Z';Object.assign(town,populationRates(town));const until=new Date(Date.parse(town.resources_updated_at)+(seed*12345+100000)*100).toISOString();
  await db.query(`update public.settlements set ${keys.map((k,i)=>`${k}=$${i+1}`).join(',')},population_ready=true where id=$${keys.length+1}`,[...keys.map(k=>town[k]),sid]);advancePopulationEconomy(town,Date.parse(until));await rpc('peris_population_accrue',[sid,until]);const actual=(await db.query('select population,wood,stone,food,gold from public.settlements where id=$1',[sid])).rows[0];for(const key of ['population','wood','stone','food','gold'])assert.ok(Math.abs(Number(actual[key])-town[key])<.01,`${seed} ${key}: ${actual[key]} != ${town[key]}`);
 }
 await login(v);await rpc('create_player',['Other']);await assert.rejects(()=>rpc('peris_population_accrue',[sid,new Date().toISOString()]),/permission/);await rpc('peris_queue_slot',[0,'housing']);await rpc('peris_debug_city',['finish']);assert.equal((await snap()).settlements[0].population_capacity,70);
 console.log('PASS · housing completion/duplicates/levels, resident fill/demolition, net food, 40 client/server growth/starvation cases, migration reruns and private helper access');
}catch(e){console.error(e.message,e.where??'');process.exitCode=1;}finally{await db.close();}
