import {FACTIONS,factionOf} from '../domain/factions';
import type {World} from '../../../shared/model/world';
import type {Command} from '../../../shared/model/commands';
export function CityDebugPanel({world,owner,cityId,target,name,level,max,busy,run}:{world:World;owner:string;cityId?:number;target:string;name:string;level:number;max:number;busy:boolean;run:(c:Command,message?:string)=>void}){
 const town=world.settlements.find(s=>s.owner_id===owner&&(cityId===undefined||s.id===cityId))!,faction=factionOf(town.faction),enabled=world.debug_enabled!==false,active=world.battles.some(b=>b.status==='active'&&(b.attacker_owner_id===owner||b.defender_owner_id===owner));
 return <div className="city-faction-controls"><label className="field-label" htmlFor="city-faction">CITY FACTION</label><select id="city-faction" value={faction} disabled={busy} onChange={e=>run({type:'setFaction',faction:e.target.value as keyof typeof FACTIONS},'City faction changed')}>{Object.entries(FACTIONS).map(([id,f])=><option key={id} value={id}>{f.name}</option>)}</select><small>{FACTIONS[faction].style}</small><button className="button debug-next-faction" disabled={busy} onClick={()=>{const ids=Object.keys(FACTIONS) as (keyof typeof FACTIONS)[];run({type:'setFaction',faction:ids[(ids.indexOf(faction)+1)%ids.length]},'City faction changed');}}>Next faction →</button>
 {enabled&&<details className="city-debug"><summary>Debug tools</summary><p>Instant changes to your city. Resources respect storage limits.</p><div className="debug-actions"><button className="button" disabled={busy||active} onClick={()=>run({type:'debugCity',action:'resources',value:1000},'Added 1,000 of each resource')}>+1,000 resources</button><button className="button" disabled={busy||active} onClick={()=>run({type:'debugCity',action:'resources',value:0},'Storage filled')}>Fill storage</button><button className="button" disabled={busy||active||!world.orders.some(o=>o.owner_id===owner&&(o.settlement_id??world.settlements[0].id)===town.id&&o.kind==='upgrade')} onClick={()=>run({type:'debugCity',action:'finish'},'Construction finished')}>Finish construction</button></div><button className="button debug-population" disabled={busy||active} onClick={()=>run({type:'debugCity',action:'population',value:0},'Housing filled with residents')}>Fill housing with residents</button><label className="field-label" htmlFor="debug-building-level">{name} · INSTANT LEVEL</label><select id="debug-building-level" disabled={busy||active||!target} value={level} onChange={e=>run({type:'debugCity',action:'level',target,value:Number(e.target.value)},'Building level changed')}>{Array.from({length:max+1},(_,n)=><option key={n} value={n}>{n===0?'0 · Demolished':`Level ${n}`}</option>)}</select><button className="button debug-demolish" disabled={busy||active||!target} onClick={()=>run({type:'debugCity',action:'demolish',target},'Building demolished')}>Demolish {name}</button><small>Demolition clears a plot and cancels its upgrade. Lowering the main building removes plots it no longer supports. Destroying a mage tower clears its research.</small>{active&&<p>Finish the current battle to use debug tools.</p>}</details>}
 </div>;
}
