import { type UnitType } from '../../army/domain/types';
import { type Resources } from '../../../shared/model/resources';
import type { Faction } from '../../factions/domain/factions';
export type Terrain = 'plains' | 'woods' | 'highlands' | 'river';
export type Difficulty = 'easy' | 'normal' | 'hard';
export type Battle = {
    id: number;
    attacker_owner_id: string;
    defender_owner_id: string | null;
    attacker_army_id: number;
    defender_army_id: number | null;
    /** Optional cosmetic overrides for isolated Quick Battles. */
    attacker_faction?: Faction;
    defender_faction?: Faction;
    status: 'active' | 'resolved';
    phase: 'deployment' | 'combat' | 'finished';
    attacker_ready: boolean;
    defender_ready: boolean;
    mode: 'pve' | 'pvp' | 'practice';
    camp_id: number | null;
    terrain: Terrain;
    difficulty: Difficulty;
    enemy_name: string;
    winner_owner_id: string | null;
    winner_side: 'attacker' | 'defender' | 'draw' | null;
    started_at: string;
    ended_at: string | null;
    last_tick_at: string;
    elapsed: number;
    result: BattleResult | null;
    mana_attacker?:number;mana_defender?:number;spell_ready_attacker?:number;spell_ready_defender?:number;
    last_spell?:{id:string;name:string;owner_id:string;at:number;target:number|null};
    rally_attacker: boolean;
    rally_defender: boolean;
};
export type FormationStatus = 'idle' | 'moving' | 'engaged' | 'routed';
export type Formation = {
    id: number;
    battle_id: number;
    owner_id: string | null;
    side: 'attacker' | 'defender';
    unit_type: UnitType;
    label: string;
    initial_soldiers: number;
    soldiers: number;
    kills: number;
    morale: number;
    stamina: number;
    facing: number;
    charge_ready: boolean;
    x: number;
    y: number;
    target_x: number;
    target_y: number;
    target_facing: number | null;
    target_formation_id: number | null;
    status: FormationStatus;
    damage_pool: number;
    attack_multiplier?: number;
    defence_multiplier?: number;
    magic_attack?:number;magic_defence?:number;magic_speed?:number;
    columns: number;
    stance: 'balanced' | 'guard' | 'aggressive';
    running: boolean;
    fire_at_will: boolean;
    updated_at: string;
};
export type BattleResult = {
    attacker_initial: number;
    defender_initial: number;
    attacker_survivors: number;
    defender_survivors: number;
    attacker_losses: number;
    defender_losses: number;
    loot: Resources;
    duration: number;
    reason: string;
};
export type BattleOrder = {
    kind: 'move' | 'attack' | 'halt' | 'stance' | 'run' | 'fire' | 'width';
    ids: number[];
    x?: number;
    y?: number;
    facing?: number;
    columns?: number;
    target?: number;
    stance?: Formation['stance'];
    enabled?: boolean;
};
export type Effect = {
    kind: 'arrow' | 'charge' | 'death' | 'route';
    x: number;
    y: number;
    tx?: number;
    ty?: number;
    side: string;
    at: number;
};
