import { useState } from 'react';
import type { World } from '../../../shared/model/world';
import type { Command } from '../../../shared/model/commands';
import type { Army } from '../../army/domain/types';
import { HERO_CLASSES, HERO_COST, HERO_STATS, EQUIPMENT_SLOTS, ARTIFACTS, armyLimit, heroBonuses, heroForArmy, heroLevel, heroPoints, heroThreshold, MAX_HERO_LEVEL, type HeroClass } from '../domain/heroes';
import { armyPosition } from '../../map/domain/movement';
import { wrappedWorldDelta } from '../../map/domain/dimensions';
import { soldierTotal } from '../../army/domain/units';

export function HeroPanel({ world, owner, army, cityId, onArmy, run, busy, now }: { world: World; owner: string; army: Army; cityId: number; onArmy?: (id: number) => void; run: (cmd: Command, message?: string) => void; busy: boolean; now: number }) {
    const [name, setName] = useState('New captain'), [heroClass, setClass] = useState<HeroClass>('knight'), [target, setTarget] = useState('');
    const [troops, setTroops] = useState({ infantry: 0, archers: 0, cavalry: 0 });
    const hero = heroForArmy(world, army.id), bonuses = heroBonuses(world, army), level = hero ? heroLevel(hero) : 1;
    const armies = world.armies.filter(a => a.owner_id === owner), city = world.settlements.find(s => s.id === cityId)!;
    const inventory = (world.hero_artifacts ?? []).filter(a => a.owner_id === owner), home = world.settlements.find(s => s.id === army.home_settlement_id)!;
    const position = armyPosition(army, now);
    const nearby = armies.filter(a => { const point = armyPosition(a, now); return a.id !== army.id && a.status === 'idle' && army.status === 'idle' && Math.hypot(wrappedWorldDelta(position.x, point.x), wrappedWorldDelta(position.y, point.y)) <= 90; });
    const receiver = nearby.find(a => a.id === Number(target)) ?? nearby[0];
    const total = troops.infantry + troops.archers + troops.cavalry;
    const rebase = army.status === 'idle' && Math.hypot(wrappedWorldDelta(position.x, city.x + 40), wrappedWorldDelta(position.y, city.y + 30)) <= 90;
    return <div className="hero-workspace">
        <section className="gameplay-card hero-card"><div className="hero-heading"><span className="hero-crest" aria-hidden="true">{hero?.class === 'mage' ? '✦' : hero?.class === 'ranger' ? '➶' : '♜'}</span><div><span className="eyebrow">{hero ? HERO_CLASSES[hero.class].name : 'COMMANDER'} · LEVEL {level}</span><h2>{hero?.name ?? 'Your captain'}</h2><small>{home.name} · {Math.round((bonuses.speed - 1) * 100)}% faster marches</small></div></div>
        {hero && <><div className="hero-experience"><div className="progress-track"><i style={{ width: `${level === MAX_HERO_LEVEL ? 100 : (hero.experience - heroThreshold(level)) / (heroThreshold(level + 1) - heroThreshold(level)) * 100}%` }}/></div><small>{hero.experience.toLocaleString()} XP{level < MAX_HERO_LEVEL ? ` / ${heroThreshold(level + 1).toLocaleString()} for level ${level + 1}` : ' · maximum level'} · {heroPoints(hero)} skill points</small></div><div className="hero-attributes">{HERO_STATS.map(stat => <div key={stat}><span>{stat === 'power' ? 'Spell power' : stat[0].toUpperCase() + stat.slice(1)}</span><strong>{bonuses[stat]}</strong><button aria-label={`Improve ${stat}`} disabled={busy || heroPoints(hero) < 1} onClick={() => run({ type: 'heroSkill', heroId: hero.id, stat }, 'Hero attribute improved')}>+</button></div>)}</div><p className="hero-effects">+{Math.round((bonuses.damage - 1) * 100)}% troop damage · {Math.round((1 - 1 / bonuses.protection) * 100)}% less damage taken · +{bonuses.mana} mana. Battle kills and victories earn experience.</p><div className="hero-equipment" aria-label="Hero equipment">{EQUIPMENT_SLOTS.map(slot => { const equipped = inventory.find(i => i.hero_id === hero.id && ARTIFACTS[i.artifact_id]?.slot === slot); const options = inventory.filter(i => (i.hero_id === null || i.hero_id === hero.id) && ARTIFACTS[i.artifact_id]?.slot === slot); return <label key={slot}><span>{slot[0].toUpperCase() + slot.slice(1)}</span><select aria-label={`${slot} artifact`} disabled={busy} value={equipped?.id ?? ''} onChange={event => { if (event.target.value) run({ type: 'equipArtifact', heroId: hero.id, artifactId: Number(event.target.value), equip: true }, 'Artifact equipped'); else if (equipped) run({ type: 'equipArtifact', heroId: hero.id, artifactId: equipped.id, equip: false }, 'Artifact returned to inventory'); }}><option value="">Empty</option>{options.map(item => <option key={item.id} value={item.id}>{ARTIFACTS[item.artifact_id].name} · {ARTIFACTS[item.artifact_id].description}</option>)}</select></label>; })}</div><small>First victories at campaign landmarks award artifacts. Unequip an item before giving it to another hero.</small></>}
        <details className="gameplay-disclosure"><summary>Nearby armies &amp; home city</summary><p>Transfers require two idle armies together, with both training queues complete.</p>{nearby.length ? <><label>Transfer to<select aria-label="Army to receive troops" value={receiver?.id ?? ''} onChange={event => setTarget(event.target.value)}>{nearby.map(a => <option key={a.id} value={a.id}>{a.name} · {soldierTotal(a)} soldiers</option>)}</select></label><div className="troop-transfer-inputs">{(['infantry', 'archers', 'cavalry'] as const).map(type => <label key={type}>{type}<input type="number" min={0} max={army[type]} value={troops[type]} onChange={event => setTroops(previous => ({ ...previous, [type]: Math.max(0, Math.min(army[type], Math.floor(Number(event.target.value) || 0))) }))}/></label>)}</div><button className="button outline" disabled={busy || !receiver || !total || soldierTotal(receiver) + total > 1000} onClick={() => { run({ type: 'transferTroops', armyId: army.id, targetArmyId: receiver!.id, ...troops }, 'Troops transferred'); setTroops({ infantry: 0, archers: 0, cavalry: 0 }); }}>Transfer troops</button></> : <small>No other idle armies nearby.</small>}<button className="button outline" disabled={busy || !rebase || home.id === city.id} onClick={() => run({ type: 'rebaseArmy', armyId: army.id, settlementId: city.id }, `${city.name} is now this army’s home`)}>Set {city.name} as home</button></details></section>
        <section className="gameplay-card hire-hero-card"><span className="eyebrow">{armies.length} / {armyLimit(world, owner)} ARMIES</span><h3>Raise another army</h3><p>Hire a hero in {city.name}. New armies start empty; train soldiers or transfer troops from a nearby army. Each city supports two armies.</p><form onSubmit={event => { event.preventDefault(); run({ type: 'recruitHero', settlementId: city.id, name, heroClass }, `${name.trim()} has raised a new army`); }}><label>Hero name<input value={name} minLength={2} maxLength={24} required onChange={event => setName(event.target.value)}/></label><fieldset className="hero-class-picker"><legend>Hero class</legend>{(Object.keys(HERO_CLASSES) as HeroClass[]).map(key => <label key={key}><input type="radio" name="hero-class" value={key} checked={heroClass === key} onChange={() => setClass(key)}/><span><strong>{HERO_CLASSES[key].name}</strong><small>{HERO_CLASSES[key].description}</small></span></label>)}</fieldset><button className="button gold" type="submit" disabled={busy || armies.length >= armyLimit(world, owner) || city.gold < HERO_COST || name.trim().length < 2}>Hire hero · {HERO_COST} gold</button></form><div className="hero-army-list">{armies.map(a => <button key={a.id} aria-pressed={a.id === army.id} onClick={() => onArmy?.(a.id)}><strong>{heroForArmy(world, a.id)?.name ?? a.name}</strong><small>{soldierTotal(a)} soldiers · {a.status === 'moving' ? 'Marching' : 'Encamped'}</small></button>)}</div></section>
    </div>;
}
