import { useState } from 'react';
import { Modal } from '../../../shared/ui/Shared';
import { Icon, UnitPortrait } from '../../../shared/ui/Icons';
import { UNITS } from '../../army/domain/units';
const terrains = [{ key: 'plains', name: 'Open country', icon: 'food', text: 'Room to manoeuvre. Infantry holds the centre while cavalry circles to attack flanks and rear.', benefit: 'Cavalry can make a full charge.' }, { key: 'woods', name: 'Oak woodland', icon: 'wood', text: 'Trees reduce ranged damage and slow movement. Infantry can use the cover to approach enemy bowmen.', benefit: 'Avoid cavalry charges through the woods.' }, { key: 'river', name: 'River crossing', icon: 'world', text: 'The stone bridge is the fastest crossing. The shallows slow the army, leaving it exposed.', benefit: 'Secure the bridge, then bring up your archers.' }, { key: 'highlands', name: 'High country', icon: 'stone', text: 'The central ridge rewards good positioning. Archers on high ground deal more damage to troops below.', benefit: 'Contest the ridge or attack from two sides.' }];
export function Codex({ onClose }: {
    onClose: () => void;
}) {
    const [tab, setTab] = useState<'campaign' | 'troops' | 'terrain' | 'controls'>('campaign');
    return <Modal title="The General's Codex" className="codex-modal" onClose={onClose}><div className="modal-tabs">{(['campaign', 'troops', 'terrain', 'controls'] as const).map(t => <button key={t} className={tab === t ? 'active' : ''} onClick={() => setTab(t)}>{t[0].toUpperCase() + t.slice(1)}</button>)}</div>
 {tab === 'campaign' ? <><p className="codex-lead">Six lost standards. One province to restore.</p><div className="codex-steps">{[{ icon: 'town', title: 'Build a home', text: 'Upgrade timber, stone, food and gold production. New levels finish on their timers and keep producing while you are away.' }, { icon: 'army', title: 'Raise your legion', text: 'Train soldiers at the keep. Three training batches can wait in the queue; your army can march when training is complete.' }, { icon: 'flag', title: 'Take the field', text: 'Choose a rebel host on the campaign map and march to it. Deploy your troops before the battle begins.' }, { icon: 'crown', title: 'Bring back the standards', text: 'Victories grant supplies and prestige. Survivors return to the keep. Replace losses and defeat all six hosts to restore Peris.' }].map(s => <article key={s.title}><Icon name={s.icon} size={30}/><div><h3>{s.title}</h3><p>{s.text}</p></div></article>)}</div><p className="codex-note">You can take the hosts in any order. Readiness advice is a guide; positioning and tactics still matter. Repeat conquered fields after their cooldown to earn supplies.</p></> :
            tab === 'troops' ? <div className="codex-troops">{(['infantry', 'archers', 'cavalry'] as const).map(t => <article key={t}><UnitPortrait type={t}/><div><span className="eyebrow">{t}</span><h3>{UNITS[t].name}</h3><p>{t === 'infantry' ? 'Your line and your shield. Guard braces against frontal charges. Attack deals more damage but leaves the formation exposed.' : t === 'archers' ? 'Keep them behind the line. Fire at will engages enemies in range; forests provide cover against their arrows. Very vulnerable in close combat.' : 'Fast, decisive and fragile when trapped. A long approach prepares a charge. Flank and rear attacks break morale; braced infantry resists them.'}</p></div></article>)}<p className="codex-note">Morale can break a living formation. Rally restores courage once per battle and can return routed survivors to the line. Running uses stamina; resting restores it.</p></div> :
                tab === 'terrain' ? <div className="codex-terrains">{terrains.map(t => <article key={t.key}><div className={`terrain-thumb terrain-${t.key}`}><Icon name={t.icon} size={40}/></div><h3>{t.name}</h3><p>{t.text}</p><small>{t.benefit}</small></article>)}</div> :
                    <><div className="controls-guide"><div><h3>Simple commands</h3><p>Select a friendly formation or a card. Click open ground to move; click an enemy to attack. Drag a box to select a group. Shift adds or removes units.</p><p>Right-click also issues orders. Right-drag draws a line and sets its facing. Group movement keeps formations together.</p><p>On touch, tap a card, choose Move or Attack, then tap the battlefield.</p></div><dl>{[['A', 'Select the whole host'], ['1–9', 'Select a formation'], ['H / G', 'Halt / Guard'], ['R', 'Rally once per battle'], ['F', 'Focus the selected unit'], ['Space', 'Pause solo / quick battle'], ['Esc', 'Battle menu'], ['Scroll / arrows', 'Zoom / pan the camera']].map(([key, text]) => <div key={key}><dt><kbd>{key}</kbd></dt><dd>{text}</dd></div>)}</dl></div><p className="codex-note">Solo battles can pause while you give orders and run at up to 3× speed. A live duel uses a common clock. Both rulers must accept and finish deployment before it starts.</p></>}
 </Modal>;
}
