import { useState } from 'react';
import { Modal } from '../../../shared/ui/Shared';
import { Icon, UnitPortrait } from '../../../shared/ui/Icons';
import { UNITS } from '../../army/domain/units';
const terrains = [{ key: 'plains', name: 'Open country', icon: 'food', text: 'Room to manoeuvre. Infantry holds the centre while cavalry circles to attack flanks and rear.', benefit: 'Cavalry can make a full charge.' }, { key: 'woods', name: 'Oak woodland', icon: 'wood', text: 'Trees reduce ranged damage and slow movement. Infantry can use the cover to approach enemy bowmen.', benefit: 'Avoid cavalry charges through the woods.' }, { key: 'river', name: 'River crossing', icon: 'world', text: 'The stone bridge is the fastest crossing. The shallows slow the army, leaving it exposed.', benefit: 'Secure the bridge, then bring up your archers.' }, { key: 'highlands', name: 'High country', icon: 'stone', text: 'The central ridge rewards good positioning. Archers on high ground deal more damage to troops below.', benefit: 'Contest the ridge or attack from two sides.' }];
export function Codex({ onClose }: {
    onClose: () => void;
}) {
    const [tab, setTab] = useState<'campaign' | 'troops' | 'terrain' | 'controls'>('campaign');
    return <Modal title="The General's Codex" className="codex-modal" onClose={onClose}><div className="modal-tabs">{(['campaign', 'troops', 'terrain', 'controls'] as const).map(t => <button key={t} className={tab === t ? 'active' : ''} onClick={() => setTab(t)}>{t[0].toUpperCase() + t.slice(1)}</button>)}</div>
 {tab === 'campaign' ? <><p className="codex-lead">Six lost standards. One province to restore.</p><div className="codex-steps">{[{ icon: 'town', title: 'Build a home', text: 'Upgrade timber, stone, food and gold production. New levels finish on their timers and keep producing while you are away.' }, { icon: 'army', title: 'Raise your legion', text: 'Choose an army and training city. Each army has three training batches and its own marching orders. Hire another commander on the Army screen; cities support two armies each.' }, { icon: 'town', title: 'Found new cities', text: 'Buildings produce empire culture. Open Cities & expansion, train three settlers at main building level 2, then send them to open land. Every city has its own stores and builders.' }, { icon: 'crown', title: 'Develop your heroes', text: 'Battle kills and victories grant hero experience. Spend level-up points on Attack, Defence, Spell power or Knowledge. First campaign victories award artifacts; equip them on the Army screen.' }, { icon: 'flag', title: 'Take the field', text: 'Choose a rebel host on the campaign map and march to it. Both armies deploy and fight automatically. Watch the encounter or inspect a formation.' }, { icon: 'crown', title: 'Bring back the standards', text: 'Victories grant supplies and prestige. Survivors return to the keep. Replace losses and defeat all six hosts to restore Peris.' }].map(s => <article key={s.title}><Icon name={s.icon} size={30}/><div><h3>{s.title}</h3><p>{s.text}</p></div></article>)}</div><p className="codex-note">You can take the hosts in any order. Readiness advice is a guide; army composition, heroes, equipment and research matter. Repeat conquered fields after their cooldown to earn supplies.</p></> :
            tab === 'troops' ? <div className="codex-troops">{(['infantry', 'archers', 'cavalry'] as const).map(t => <article key={t}><UnitPortrait type={t}/><div><span className="eyebrow">{t}</span><h3>{UNITS[t].name}</h3><p>{t === 'infantry' ? 'Your front line. The AI advances toward suitable targets and braces against nearby cavalry.' : t === 'archers' ? 'The AI keeps archers at firing distance and pulls back from approaching melee troops. Forests provide cover against arrows. Archers are vulnerable when cornered.' : 'Fast, decisive and fragile when trapped. A long approach prepares a charge. Flank and rear attacks break morale; braced infantry resists them.'}</p></div></article>)}<p className="codex-note">Morale can break a living formation. The AI rallies each army once when its surviving soldiers need it, and may return routed survivors to the line. Running uses stamina; resting restores it.</p></div> :
                tab === 'terrain' ? <div className="codex-terrains">{terrains.map(t => <article key={t.key}><div className={`terrain-thumb terrain-${t.key}`}><Icon name={t.icon} size={40}/></div><h3>{t.name}</h3><p>{t.text}</p><small>{t.benefit}</small></article>)}</div> :
                    <><div className="controls-guide"><div><h3>Automatic battles</h3><p>Both armies choose targets, advance, fight, rally and cast researched spells automatically. Prepare your troop mix, commander, equipment and research before marching.</p><p>Click either army to inspect its soldiers, target, morale and stamina. Drag the battlefield to pan and scroll to zoom.</p><p>Solo and practice battles support pause and 1×, 2× or 3× viewing speed.</p></div><dl>{[['A', 'Select the whole host'], ['1–9', 'Select a formation'], ['F', 'Focus the selected unit'], ['Space', 'Pause solo / quick battle'], ['Esc', 'Battle menu'], ['Scroll / arrows', 'Zoom / pan the camera']].map(([key, text]) => <div key={key}><dt><kbd>{key}</kbd></dt><dd>{text}</dd></div>)}</dl></div><p className="codex-note">A live duel uses the server clock and starts automatically when accepted. Manual movement, attack orders, rallies and spell casting are disabled for both players.</p></>}
 </Modal>;
}
