import type { World } from '../../../shared/model/world';
import type { Resources } from '../../../shared/model/resources';
export type SpellTarget = 'ally'|'enemy'|'allies'|'enemies';
export type Spell = {id:string;name:string;school:string;level:number;mana:number;target:SpellTarget;description:string;damage:number;heal:number;morale:number;stamina:number;attack:number;defence:number;speed:number;radius:number;chain:number;revive:boolean};
export type SpellResearch = {settlement_id:number;spell_id:string;researched_at:string};
export const SPELLS:readonly Spell[] = [
  {
    "id": "spark",
    "name": "Spark",
    "school": "Fire",
    "level": 1,
    "mana": 5,
    "target": "enemy",
    "damage": 8,
    "heal": 0,
    "morale": 0,
    "stamina": 0,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": false,
    "description": "Deal 8 casualties to one enemy formation."
  },
  {
    "id": "mend",
    "name": "Mend",
    "school": "Light",
    "level": 1,
    "mana": 5,
    "target": "ally",
    "damage": 0,
    "heal": 8,
    "morale": 0,
    "stamina": 0,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": false,
    "description": "Restore up to 8 soldiers to one active friendly formation."
  },
  {
    "id": "ice-bolt",
    "name": "Ice Bolt",
    "school": "Water",
    "level": 2,
    "mana": 8,
    "target": "enemy",
    "damage": 12,
    "heal": 0,
    "morale": 0,
    "stamina": -12,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": false,
    "description": "Deal 12 casualties and remove 12 stamina from one enemy."
  },
  {
    "id": "stone-skin",
    "name": "Stone Skin",
    "school": "Earth",
    "level": 2,
    "mana": 8,
    "target": "ally",
    "damage": 0,
    "heal": 0,
    "morale": 0,
    "stamina": 0,
    "attack": 0,
    "defence": 0.2,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": false,
    "description": "Reduce one friendly formation’s incoming damage by 20% for this battle."
  },
  {
    "id": "lightning",
    "name": "Lightning",
    "school": "Air",
    "level": 3,
    "mana": 10,
    "target": "enemy",
    "damage": 18,
    "heal": 0,
    "morale": 0,
    "stamina": 0,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": false,
    "description": "Deal 18 casualties to one enemy formation."
  },
  {
    "id": "haste",
    "name": "Haste",
    "school": "Air",
    "level": 3,
    "mana": 10,
    "target": "ally",
    "damage": 0,
    "heal": 0,
    "morale": 0,
    "stamina": 0,
    "attack": 0,
    "defence": 0,
    "speed": 0.25,
    "radius": 0,
    "chain": 0,
    "revive": false,
    "description": "Give one friendly formation +25% movement speed for this battle."
  },
  {
    "id": "fireball",
    "name": "Fireball",
    "school": "Fire",
    "level": 4,
    "mana": 15,
    "target": "enemy",
    "damage": 12,
    "heal": 0,
    "morale": 0,
    "stamina": 0,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 100,
    "chain": 0,
    "revive": false,
    "description": "Deal 12 casualties to enemies within 100 paces of the target."
  },
  {
    "id": "bless",
    "name": "Bless",
    "school": "Light",
    "level": 4,
    "mana": 12,
    "target": "ally",
    "damage": 0,
    "heal": 0,
    "morale": 0,
    "stamina": 0,
    "attack": 0.15,
    "defence": 0,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": false,
    "description": "Give one friendly formation +15% damage for this battle."
  },
  {
    "id": "terror",
    "name": "Terror",
    "school": "Shadow",
    "level": 5,
    "mana": 15,
    "target": "enemy",
    "damage": 0,
    "heal": 0,
    "morale": -25,
    "stamina": 0,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": false,
    "description": "Remove 25 morale from one enemy; broken formations may rout."
  },
  {
    "id": "courage",
    "name": "Courage",
    "school": "Light",
    "level": 5,
    "mana": 18,
    "target": "allies",
    "damage": 0,
    "heal": 0,
    "morale": 12,
    "stamina": 0,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": false,
    "description": "Restore 12 morale to all active friendly formations."
  },
  {
    "id": "chain-lightning",
    "name": "Chain Lightning",
    "school": "Air",
    "level": 6,
    "mana": 22,
    "target": "enemy",
    "damage": 18,
    "heal": 0,
    "morale": 0,
    "stamina": 0,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 0,
    "chain": 3,
    "revive": false,
    "description": "Strike the target and two nearest enemies for 18, 12 and 6 casualties."
  },
  {
    "id": "sanctuary",
    "name": "Sanctuary",
    "school": "Light",
    "level": 6,
    "mana": 22,
    "target": "allies",
    "damage": 0,
    "heal": 12,
    "morale": 0,
    "stamina": 0,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": false,
    "description": "Restore up to 12 soldiers to every active friendly formation."
  },
  {
    "id": "frost-nova",
    "name": "Frost Nova",
    "school": "Water",
    "level": 7,
    "mana": 25,
    "target": "enemy",
    "damage": 12,
    "heal": 0,
    "morale": 0,
    "stamina": -30,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 120,
    "chain": 0,
    "revive": false,
    "description": "Deal 12 casualties and remove 30 stamina from enemies within 120 paces."
  },
  {
    "id": "battle-trance",
    "name": "Battle Trance",
    "school": "Shadow",
    "level": 7,
    "mana": 25,
    "target": "allies",
    "damage": 0,
    "heal": 0,
    "morale": 0,
    "stamina": 25,
    "attack": 0.15,
    "defence": 0,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": false,
    "description": "Give all active friendly formations +15% damage and 25 stamina."
  },
  {
    "id": "meteor",
    "name": "Meteor",
    "school": "Earth",
    "level": 8,
    "mana": 32,
    "target": "enemy",
    "damage": 22,
    "heal": 0,
    "morale": 0,
    "stamina": 0,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 150,
    "chain": 0,
    "revive": false,
    "description": "Deal 22 casualties to enemies within 150 paces of the target."
  },
  {
    "id": "resurrection",
    "name": "Resurrection",
    "school": "Light",
    "level": 8,
    "mana": 30,
    "target": "ally",
    "damage": 0,
    "heal": 25,
    "morale": 65,
    "stamina": 0,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": true,
    "description": "Return up to 25 lost soldiers to one friendly formation, even if fallen or routed, and restore morale to at least 65."
  },
  {
    "id": "storm",
    "name": "Storm",
    "school": "Air",
    "level": 9,
    "mana": 40,
    "target": "enemies",
    "damage": 18,
    "heal": 0,
    "morale": 0,
    "stamina": 0,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": false,
    "description": "Deal 18 casualties to every active enemy formation."
  },
  {
    "id": "aegis",
    "name": "Aegis",
    "school": "Earth",
    "level": 9,
    "mana": 38,
    "target": "allies",
    "damage": 0,
    "heal": 0,
    "morale": 0,
    "stamina": 0,
    "attack": 0,
    "defence": 0.4,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": false,
    "description": "Reduce all active friendly formations’ incoming damage by 40% for this battle."
  },
  {
    "id": "inferno",
    "name": "Inferno",
    "school": "Fire",
    "level": 10,
    "mana": 50,
    "target": "enemies",
    "damage": 28,
    "heal": 0,
    "morale": -15,
    "stamina": 0,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": false,
    "description": "Deal 28 casualties and remove 15 morale from every active enemy formation."
  },
  {
    "id": "phoenix",
    "name": "Phoenix",
    "school": "Light",
    "level": 10,
    "mana": 50,
    "target": "allies",
    "damage": 0,
    "heal": 30,
    "morale": 80,
    "stamina": 0,
    "attack": 0,
    "defence": 0,
    "speed": 0,
    "radius": 0,
    "chain": 0,
    "revive": true,
    "description": "Return up to 30 lost soldiers to every friendly formation, even if fallen or routed, and restore morale to at least 80."
  }
];
export const spellById=(id:string)=>SPELLS.find(s=>s.id===id);
export const towerLevel=(w:World,sid:number)=>w.city_slots?.find(s=>s.settlement_id===sid&&s.building_type==='mage_tower')?.level??0;
export const researchCost=(spell:Spell):Resources=>({wood:spell.level*40,stone:spell.level*55,food:0,gold:spell.level*70});
export const knowsSpell=(w:World,sid:number,id:string)=>w.spell_research?.some(s=>s.settlement_id===sid&&s.spell_id===id)??false;
export const maximumMana=(level:number)=>level>0?20+level*10:0;
export const SPELL_COOLDOWN=8;
