import type { Battle, BattleResult, World } from '../types/game'
import { clock, mySide } from '../game/rules'
import { Cost } from './Shared'
import { Icon } from './Icons'
export function ResultBody({result,won,side='attacker',enemyName}:{result:BattleResult;won:boolean;side?:'attacker'|'defender';enemyName:string}){
 const myLoss=side==='attacker'?result.attacker_losses:result.defender_losses,enemyLoss=side==='attacker'?result.defender_losses:result.attacker_losses,mySurvivors=side==='attacker'?result.attacker_survivors:result.defender_survivors
 return <><div className={`victory-seal ${won?'won':''}`}><Icon name={won?'crown':'shield'} size={42}/></div><span className="eyebrow">{won?'THE FIELD IS YOURS':'THE HOST REGROUPS'}</span><h2>{won?'Victory':'Defeat'}</h2><p>{enemyName} · {result.reason} · {clock(result.duration)}</p><div className="result-stats"><div><b>{mySurvivors}</b><small>survivors</small></div><div><b>{myLoss}</b><small>your losses</small></div><div><b>{enemyLoss}</b><small>enemy losses</small></div></div>{won&&Object.values(result.loot??{}).some(n=>n>0)&&<div className="result-loot"><span className="eyebrow">SPOILS OF WAR</span><Cost cost={result.loot}/></div>}<p className="muted">Surviving campaign troops regroup at the keep. Recruit replacements before your next march.</p></>
}
export function Chronicle({world,playerId,onReport}:{world:World;playerId:string;onReport:(b:Battle)=>void}){
 const player=world.players.find(p=>p.id===playerId)!
 return <section className="chronicle"><div className="view-heading"><div><span className="eyebrow">THE CHRONICLE</span><h1>Deeds worth remembering</h1><p>The record of your growing realm and its campaigns.</p></div><span className="tag">{player.prestige} prestige</span></div><div className="chronicle-metrics"><div><Icon name="crown"/><b>{player.victories}</b><span>Victories</span></div><div><Icon name="army"/><b>{player.recruits}</b><span>Soldiers trained</span></div><div><Icon name="town"/><b>{player.upgrades}</b><span>Buildings developed</span></div><div><Icon name="flag"/><b>{world.progress.filter(p=>p.owner_id===playerId&&p.defeated>0).length} / 6</b><span>Rebel hosts defeated</span></div></div>
 <div className="reports-heading"><h3>Battle reports</h3><span>{world.reports.length} recorded</span></div>{!world.reports.length?<div className="empty-state"><Icon name="report" size={40}/><h3>Your story is still unwritten.</h3><p>Select The broken standard on the world map to begin your first campaign.</p></div>:<div className="report-list">{world.reports.map(r=>{const b=world.battles.find(b=>b.id===r.battle_id);const side=b?mySide(b,playerId):'attacker';return <button key={r.id} onClick={()=>{if(b)onReport({...b,result:r.result})}}><Icon name={r.won?'crown':'shield'}/><div><strong>{r.title}</strong><small>{new Date(r.created_at).toLocaleString()}</small></div><span className={r.won?'win':'loss'}>{r.won?'Victory':'Defeat'}</span><span>{side==='attacker'?r.result.attacker_losses:r.result.defender_losses} losses</span><Icon name="arrow" size={16}/></button>})}</div>}
 </section>
}
