import { useState } from 'react';
import { type Difficulty, type Terrain } from '../../battle/domain/types';
import { readSolo } from '../../../platform/storage/solo';
import { campaignRank, conquered } from '../../campaign/domain/progression';
import { Crest, Icon } from '../../../shared/ui/Icons';
import { Modal } from '../../../shared/ui/Shared';
export type Doctrine = 'balanced' | 'infantry' | 'cavalry';
export function Login({ onSolo, onOnline, onPractice, onSettings, onCodex, busy, error }: {
    onSolo: (name: string, resume: boolean) => void;
    onOnline: (name: string) => void;
    onPractice: (terrain: Terrain, difficulty: Difficulty, doctrine: Doctrine) => void;
    onSettings: () => void;
    onCodex: () => void;
    busy: boolean;
    error: string | null;
}) {
    const [mode, setMode] = useState<'solo' | 'online'>('solo'), [name, setName] = useState('Rex'), [setup, setSetup] = useState(false), [newGame, setNewGame] = useState(false), [terrain, setTerrain] = useState<Terrain>('plains'), [difficulty, setDifficulty] = useState<Difficulty>('normal'), [doctrine, setDoctrine] = useState<Doctrine>('balanced'), [credits, setCredits] = useState(false);
    const saved = readSolo(), standalone = location.protocol === 'file:', done = saved ? conquered(saved, 'solo-ruler').size : 0;
    const terrainCopy = { plains: 'Open ground, room for flanks and decisive charges.', woods: 'Oak cover protects against arrows and slows cavalry.', river: 'Control the stone bridge and cover the crossing.', highlands: 'Take the ridge to give your archers the advantage.' };
    return <main className="launcher">
  <div className="launcher-art"/><div className="launcher-shade"/><div className="launcher-dust" aria-hidden="true">{Array.from({ length: 12 }, (_, i) => <i key={i} style={{ left: `${15 + i * 7}%`, animationDelay: `${-i * 1.8}s` }}/>)}</div>
  <div className="launcher-top"><span>THE AGE OF AMBITION</span><div><button onClick={onCodex}><Icon name="book" size={17}/>Codex</button><button onClick={onSettings}><Icon name="settings" size={17}/>Settings</button></div></div>
  <section className="launcher-panel"><Crest /><div className="eyebrow">A PROVINCE LOST. A STANDARD RAISED.</div><h1>PERIS</h1><div className="title-rule"/><p className="launcher-intro">Build a home. Lead a legion.<br />Bring the six standards back.</p>
   <div className="mode-tabs"><button className={mode === 'solo' ? 'active' : ''} onClick={() => setMode('solo')}>The campaign</button><button className={mode === 'online' ? 'active' : ''} disabled={standalone} title={standalone ? 'Play multiplayer on the deployed game' : undefined} onClick={() => setMode('online')}>Shared world</button></div>
   {mode === 'solo' ? <>{saved ? <><div className="menu-save"><span className="eyebrow">YOUR REALM AWAITS</span><strong>{saved.settlements[0].name}</strong><small>{campaignRank(done)} · {done} / 6 standards</small><div className="menu-standards">{[1, 2, 3, 4, 5, 6].map(n => <i key={n} className={conquered(saved, 'solo-ruler').has(n) ? 'claimed' : ''}><Icon name="flag" size={17}/></i>)}</div></div><button className="button gold launch-cta" disabled={busy} onClick={() => onSolo('', true)}>Continue campaign <Icon name="arrow"/></button><button className="menu-secondary" disabled={busy} onClick={() => setNewGame(true)}>Begin a new campaign</button></> : <><button className="button gold launch-cta" disabled={busy} onClick={() => setNewGame(true)}>Begin your campaign <Icon name="arrow"/></button><p className="mode-description">One settlement. Six rebel hosts. Your decisions shape the restoration of Peris.</p></>}</> :
            <form onSubmit={e => { e.preventDefault(); onOnline(name); }}><label className="field-label" htmlFor="ruler-name">YOUR RULER NAME</label><input id="ruler-name" value={name} onChange={e => setName(e.target.value)} maxLength={20} autoComplete="off" disabled={busy}/><button className="button gold launch-cta" disabled={busy}>{busy ? 'Opening the gates…' : 'Enter the shared world'}<Icon name="arrow"/></button><p className="mode-description">Develop a realm alongside other rulers. Invite a rival to a live duel when both legions are ready. Your existing account returns to its realm.</p></form>}
   <button className="quick-battle-link" onClick={() => setSetup(true)} disabled={busy}><Icon name="army"/>Quick battle <span>Take the field immediately <Icon name="arrow" size={14}/></span></button>
   {error && <div className="alert error" role="alert">{error}</div>}{busy && <div className="loading-bar" aria-label="Connecting to the shared world"><i /></div>}
  </section>
  <div className="launcher-bottom"><button onClick={() => setCredits(true)}>Original world & artwork</button><span>THE SIX STANDARDS · V0.7</span></div>
  {newGame && <Modal title="Raise your standard" className="new-campaign-modal" onClose={() => setNewGame(false)}><p>How will the province remember you?</p><form onSubmit={e => { e.preventDefault(); if (name.trim().length >= 2) {
        onSolo(name, false);
        setNewGame(false);
    } }}><label className="field-label" htmlFor="new-ruler">RULER NAME</label><input id="new-ruler" value={name} onChange={e => setName(e.target.value)} minLength={2} maxLength={20} required autoComplete="off"/>{saved && <div className="new-realm-note"><Icon name="time"/><p>Your current realm will be kept as the previous realm. Restore it anytime in Settings → Campaign saves.</p></div>}<button className="button gold" disabled={name.trim().length < 2}>Found your realm <Icon name="arrow"/></button></form></Modal>}
  {setup && <Modal title="Take the field" className="quick-setup" onClose={() => setSetup(false)}><span className="eyebrow">A SINGLE BATTLE. YOUR COMMAND.</span><p>Choose your terrain, host, and opponent. Campaign troops and supplies are unaffected.</p><label className="field-label">BATTLEFIELD</label><div className="terrain-options">{(['plains', 'woods', 'highlands', 'river'] as Terrain[]).map(t => <button key={t} className={terrain === t ? 'selected' : ''} onClick={() => setTerrain(t)}><Icon name={t === 'river' ? 'world' : t === 'woods' ? 'wood' : t === 'highlands' ? 'stone' : 'food'} size={28}/><span>{t === 'plains' ? 'Open country' : t === 'woods' ? 'Woodland' : t === 'highlands' ? 'High country' : 'River crossing'}</span></button>)}</div><div className="setup-terrain-note"><Icon name="flag" size={18}/>{terrainCopy[terrain]}</div><label className="field-label">YOUR HOST</label><div className="doctrine-options">{([{ id: 'balanced', name: 'Balanced legion', icon: 'army', description: '200 infantry · 90 archers · 36 cavalry' }, { id: 'infantry', name: 'The iron wall', icon: 'shield', description: '320 infantry · 60 archers · 12 cavalry' }, { id: 'cavalry', name: 'The sweeping wing', icon: 'horse', description: '160 infantry · 60 archers · 90 cavalry' }] as const).map(d => <button key={d.id} className={doctrine === d.id ? 'selected' : ''} onClick={() => setDoctrine(d.id)}><Icon name={d.icon}/><span><strong>{d.name}</strong><small>{d.description}</small></span></button>)}</div><label className="field-label" htmlFor="difficulty">ENEMY COMMANDER</label><select id="difficulty" value={difficulty} onChange={e => setDifficulty(e.target.value as Difficulty)}><option value="easy">Recruit · a forgiving first battle</option><option value="normal">Veteran · an even contest</option><option value="hard">General · superior forces and aggressive tactics</option></select><button className="button gold" onClick={() => onPractice(terrain, difficulty, doctrine)}>Deploy your army <Icon name="arrow"/></button></Modal>}
  {credits && <Modal title="A world of our own" onClose={() => setCredits(false)}><Crest /><p>Peris is an original frontier province inspired by classical strategy. Its city, landscape and portraits were created for this game. Terrain, soldiers, formations and effects are drawn by the game itself.</p><p>The ambient score and command sounds are generated in the browser. Open Sans is included under the SIL Open Font License. No borrowed Total War assets are used.</p><button className="button gold" onClick={() => setCredits(false)}>Return to Peris</button></Modal>}
 </main>;
}
