import type {Faction} from '../../factions/domain/factions';
import { type Resources } from '../../../shared/model/resources';
export type BuildingType = 'lumber' | 'quarry' | 'farm' | 'market' | 'barracks' | 'stables' | 'wall' | 'storehouse';
export type Settlement = Resources & {
    id: number;
    settlers?: number;
    development_points?: number;
    owner_id: string;
    name: string;
    x: number;
    y: number;
    wood_rate: number;
    stone_rate: number;
    food_rate: number;
    gold_rate: number;
    resources_updated_at: string;
    created_at: string;
    capacity: number;
    food_capacity?: number;
    faction?: Faction;
    /** Public, completed map silhouette; no private stocks or building lists. */
    map_development?: 1 | 2 | 3 | 4 | 5;
    population?: number;
    population_capacity?: number;
    workers_required?: number;
    wood_bonus?: number;
    stone_bonus?: number;
    food_bonus?: number;
    gold_bonus?: number;
    food_gross_rate?: number;
    food_upkeep?: number;
    field_wood_rate?: number;
    field_stone_rate?: number;
    field_food_rate?: number;
    field_gold_rate?: number;
};
export type Building = {
    id: number;
    settlement_id: number;
    building_type: BuildingType;
    level: number;
    updated_at: string;
};
