import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getCell } from '../src/features/map/domain/worldGrid.ts';
import { WORLD_COLS, WORLD_ROWS, CELL_SIZE, WORLD_MAP_SEED, WORLD_MAP_VERSION } from '../src/features/map/domain/dimensions.ts';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
if (WORLD_COLS !== 200 || WORLD_ROWS !== 200 || CELL_SIZE !== 128) throw Error('Server format requires 200 × 200 fields of size 128');
const terrainNames = ['grassland', 'forest', 'mountain', 'farmland', 'desert', 'snow', 'marsh', 'river', 'water', 'coast', 'darkland'];
const mask = Buffer.alloc(WORLD_COLS * WORLD_ROWS / 8), terrain = Buffer.alloc(WORLD_COLS * WORLD_ROWS);
let land = 0;
for (let row = 0; row < WORLD_ROWS; row++) for (let col = 0; col < WORLD_COLS; col++) {
 const index = row * WORLD_COLS + col, type = getCell(col - 100, row - 100).terrain;
 terrain[index] = terrainNames.indexOf(type);
 if (type !== 'water') { mask[index >> 3] |= 1 << (index & 7); land++; }
}
const source = `-- Generated by node --import tsx scripts/build-world.mjs. Do not edit these bytes.
-- Version ${WORLD_MAP_VERSION}, seed ${WORLD_MAP_SEED}; walkability bits and terrain bytes share row-major indexing.
create table if not exists public.peris_world_map(
 id integer primary key check(id=1),seed integer not null,cols integer not null,rows integer not null,
 cell_size integer not null,walkable bytea not null
);
alter table public.peris_world_map add column if not exists version integer not null default 3;
alter table public.peris_world_map add column if not exists terrain bytea;
alter table public.peris_world_map add column if not exists legacy_walkable bytea;
alter table public.peris_world_map drop constraint if exists peris_world_map_walkable_check;
alter table public.peris_world_map drop constraint if exists peris_world_map_terrain_check;
alter table public.peris_world_map enable row level security;
revoke all on public.peris_world_map from public,anon,authenticated;
-- Never silently relocate an existing player if their occupied field would become sea.
do $$ begin
 if exists(select 1 from public.settlements where get_bit(decode('${mask.toString('hex')}','hex'),(floor(y/128)::integer+100)*200+floor(x/128)::integer+100)=0) then
  raise exception 'An occupied settlement would become sea. Review its terrain before applying the map migration.';
 end if;
end $$;
update public.peris_world_map set legacy_walkable=walkable where version<4 and legacy_walkable is null;
insert into public.peris_world_map(id,seed,cols,rows,cell_size,walkable,terrain,version)
values(1,${WORLD_MAP_SEED},200,200,128,decode('${mask.toString('hex')}','hex'),decode('${terrain.toString('hex')}','hex'),${WORLD_MAP_VERSION})
on conflict(id)do update set seed=excluded.seed,cols=excluded.cols,rows=excluded.rows,cell_size=excluded.cell_size,
 walkable=excluded.walkable,terrain=excluded.terrain,version=excluded.version;
alter table public.peris_world_map add constraint peris_world_map_walkable_check check(octet_length(walkable)=5000);
alter table public.peris_world_map add constraint peris_world_map_terrain_check check(octet_length(terrain)=40000);

create or replace function public.peris_world_walkable(p_x numeric,p_y numeric)returns boolean
language sql stable security definer set search_path='' as $$
 select coalesce((select get_bit(walkable,(floor(public.peris_wrap_world(p_y)/128)::integer+100)*200+floor(public.peris_wrap_world(p_x)/128)::integer+100)=1
 from public.peris_world_map where id=1),false)
$$;

-- Preserve every old site ID and coordinate. New sites require eight dry neighbours.
insert into public.spawn_points(id,x,y)
select site.id,site.x,site.y from (
 select 10013+row_index*50+column_index as id,(column_index*4-98)*128+64 as x,(row_index*4-98)*128+64 as y
 from generate_series(0,49) as rows(row_index) cross join generate_series(0,49) as columns(column_index)
) site
where not exists(select 1 from generate_series(-1,1) dx cross join generate_series(-1,1) dy
 where not public.peris_world_walkable(site.x+dx*128,site.y+dy*128))
 and not exists(select 1 from public.spawn_points existing where existing.x=site.x and existing.y=site.y)
on conflict(id)do nothing;

`;
const target = path.join(root, 'supabase/modules/map/world-terrain.sql');
if (process.argv.includes('--check')) {
 if ((await fs.readFile(target, 'utf8')).replace(/\r\n/g, '\n') !== source) throw Error('Stale world bytes: run node --import tsx scripts/build-world.mjs');
} else await fs.writeFile(target, source);
console.log(`World bytes ${process.argv.includes('--check') ? 'match' : 'generated'}: ${land} dry fields, ${mask.length} walkability bytes, ${terrain.length} terrain bytes`);
