import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getCell } from '../src/features/map/domain/worldGrid.ts';
import { WORLD_COLS, WORLD_ROWS, CELL_SIZE } from '../src/features/map/domain/dimensions.ts';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
if(WORLD_COLS!==200||WORLD_ROWS!==200||CELL_SIZE!==128)throw Error('The server world format requires 200×200 cells of size128');
const mask=Buffer.alloc(WORLD_COLS*WORLD_ROWS/8);
let land=0;
for(let row=0;row<WORLD_ROWS;row++)for(let col=0;col<WORLD_COLS;col++){
 const index=row*WORLD_COLS+col;
 if(getCell(col-WORLD_COLS/2,row-WORLD_ROWS/2).terrain!=='water'){mask[index>>3]|=1<<(index&7);land++;}
}
const source=`-- Generated by node --import tsx scripts/build-world.mjs. Do not edit the mask.
-- One bit per field (row-major, least-significant bit first), seed98213.
create table if not exists public.peris_world_map(
 id integer primary key check(id=1),seed integer not null,cols integer not null,rows integer not null,
 cell_size integer not null,walkable bytea not null
);
-- Replace the former 20 kB mask constraint before storing the new 5 kB mask.
alter table public.peris_world_map drop constraint if exists peris_world_map_walkable_check;
alter table public.peris_world_map enable row level security;
revoke all on public.peris_world_map from public,anon,authenticated;
insert into public.peris_world_map(id,seed,cols,rows,cell_size,walkable)
values(1,98213,200,200,128,decode('${mask.toString('hex')}','hex'))
on conflict(id)do update set seed=excluded.seed,cols=excluded.cols,rows=excluded.rows,cell_size=excluded.cell_size,walkable=excluded.walkable;
alter table public.peris_world_map add constraint peris_world_map_walkable_check check(octet_length(walkable)=5000);

create or replace function public.peris_world_walkable(p_x numeric,p_y numeric)returns boolean
language sql stable security definer set search_path='' as $$
 select case when p_x>=-12800 and p_x<12800 and p_y>=-12800 and p_y<12800 then
  coalesce((select get_bit(walkable,((floor(p_y/128)::integer+100)*200+floor(p_x/128)::integer+100))=1 from public.peris_world_map where id=1),false)
 else false end
$$;

-- Reserve a new ID range so a former 400-field world's sites never move.
-- Keep all twelve original sites; only new land fields receive new sites.
insert into public.spawn_points(id,x,y)
select site.id,site.x,site.y from (
 select 10013 + row_index * 50 + column_index as id,
        (column_index * 4 - 98) * 128 + 64 as x,
        (row_index * 4 - 98) * 128 + 64 as y
 from generate_series(0,49) as rows(row_index)
 cross join generate_series(0,49) as columns(column_index)
) site
where public.peris_world_walkable(site.x,site.y)
 and not exists(select 1 from public.spawn_points existing where existing.x=site.x and existing.y=site.y)
on conflict(id) do nothing;

`;
const target=path.join(root,'supabase/modules/map/world-terrain.sql');
if(process.argv.includes('--check')){
 if((await fs.readFile(target,'utf8')).replace(/\r\n/g,'\n')!==source)throw Error('Stale world mask: run node --import tsx scripts/build-world.mjs');
}else await fs.writeFile(target,source);
console.log(`${process.argv.includes('--check')?'World mask matches':'World mask generated'}: ${land} walkable fields, ${mask.length} bytes`);
