import { useEffect, useMemo, useState, useSyncExternalStore } from 'react'
import { Login } from './components/Login'
import { Crest, Icon } from './components/Icons'
import { Cost, Modal } from './components/Shared'
import { SettlementView } from './components/SettlementView'
import { ArmyView } from './components/ArmyView'
import { BattleView } from './components/BattleView'
import { Chronicle, ResultBody } from './components/Chronicle'
import { GameCanvas } from './game/GameCanvas'
import { armyPosition, clock, dist, liveResources, lootFor, mySide, playerName, QUESTS, RESOURCES, soldierTotal } from './game/rules'
import type { Battle, Difficulty, MapSelection, Terrain } from './types/game'
import type { Command, GameEngine } from './lib/local'
import { createSolo, LocalEngine, readSolo } from './lib/local'
import { enterOnline, OnlineEngine } from './lib/online'
import { audioEnabled, setAudio, tone } from './lib/audio'

export default function App(){
 const [engine,setEngine]=useState<GameEngine|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null)
 useEffect(()=>()=>engine?.destroy(),[engine])
 const solo=(name:string,resume:boolean)=>{
  const save=resume?readSolo():null
  if(!save&&(name.trim().length<2||name.trim().length>20)){setError('Choose a ruler name of 2–20 characters.');return}
  setError(null);setEngine(new LocalEngine(save??createSolo(name.trim())))
 }
 const online=async(name:string)=>{setBusy(true);setError(null);try{setEngine(await enterOnline(name))}catch(e){setError(e instanceof Error?e.message:'Could not join the world.')}finally{setBusy(false)}}
 const practice=(terrain:Terrain,difficulty:Difficulty)=>{const e=new LocalEngine(createSolo('Your legion'),false);e.startPractice(terrain,difficulty);setEngine(e);setError(null)}
 if(!engine)return <Login onSolo={solo} onOnline={name=>void online(name)} onPractice={practice} busy={busy} error={error}/>
 return <Realm engine={engine} onExit={()=>{engine.destroy();setEngine(null)}}/>
}

function Realm({engine,onExit}:{engine:GameEngine;onExit:()=>void}){
 const world=useSyncExternalStore(engine.subscribe,()=>engine.snapshot)
 const [view,setView]=useState<'world'|'settlement'|'army'|'chronicle'>('world'),[selection,setSelection]=useState<MapSelection>({kind:'camp',id:1}),[moveMode,setMoveMode]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState<{text:string;error:boolean}|null>(null),[help,setHelp]=useState(false),[settings,setSettings]=useState(false),[sound,setSound]=useState(audioEnabled()),[report,setReport]=useState<Battle|null>(null),[rename,setRename]=useState(''),[time,setTime]=useState(Date.now())
 const [seenReports]=useState(()=>new Set(world.battles.filter(b=>b.status==='resolved').map(b=>b.id)))
 const offset=useMemo(()=>Date.parse(world.server_now)-Date.now(),[world.server_now]),now=time+offset
 const player=world.players.find(p=>p.id===engine.playerId)!,town=world.settlements.find(s=>s.owner_id===engine.playerId)!,army=world.armies.find(a=>a.owner_id===engine.playerId)!,resources=liveResources(town,now),active=world.battles.find(b=>b.status==='active')
 useEffect(()=>{const t=window.setInterval(()=>setTime(Date.now()),250);return()=>window.clearInterval(t)},[])
 useEffect(()=>{if(!notice)return;const t=window.setTimeout(()=>setNotice(null),4500);return()=>window.clearTimeout(t)},[notice])
 useEffect(()=>{for(const b of world.battles){if(b.status==='resolved'&&!seenReports.has(b.id)){seenReports.add(b.id);setReport(b);tone(b.winner_owner_id===engine.playerId?'success':'error')}}},[world,engine.playerId,seenReports])
 const run=async(cmd:Command,message?:string)=>{
  if(busy&&cmd.type!=='order')return
  if(cmd.type!=='order')setBusy(true)
  try{await engine.command(cmd);if(message)setNotice({text:message,error:false});tone('order')}
  catch(e){setNotice({text:e instanceof Error?e.message:'The order could not be completed.',error:true});tone('error')}
  finally{if(cmd.type!=='order')setBusy(false)}
 }
 const dispatch=(c:Command,m?:string)=>void run(c,m)
 const exportSave=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(world,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Peris-campaign-save.json';a.click();window.setTimeout(()=>URL.revokeObjectURL(url),500)}
 const selectedCamp=selection?.kind==='camp'?world.camps.find(c=>c.id===selection.id):null
 const selectedTown=selection?.kind==='settlement'?world.settlements.find(s=>s.id===selection.id):null
 const selectedArmy=selection?.kind==='army'?world.armies.find(a=>a.id===selection.id):null
 const moving=army.status==='moving'&&Date.parse(army.arrival_at)>now
 const cooldown=selectedCamp?world.progress.find(p=>p.camp_id===selectedCamp.id&&p.owner_id===engine.playerId):null
 const outgoing=world.challenges.filter(c=>c.attacker_owner_id===engine.playerId),incoming=world.challenges.filter(c=>c.defender_owner_id===engine.playerId)
 const navigate=(v:typeof view)=>{setView(v);setMoveMode(false)}
 return <>
  {active?<BattleView world={world} battle={active} engine={engine} run={dispatch} onHelp={()=>setHelp(true)}/>:<div className="realm-shell">
   <nav className="side-rail" aria-label="Game navigation"><button className="brand-home" title="World map" onClick={()=>navigate('world')}><Crest small/></button><div className="rail-links">{([{id:'world',icon:'world',label:'World'},{id:'settlement',icon:'town',label:'City'},{id:'army',icon:'army',label:'Army'},{id:'chronicle',icon:'report',label:'Deeds'}]as const).map(tab=><button key={tab.id} className={view===tab.id?'active':''} title={tab.label} onClick={()=>navigate(tab.id)}><Icon name={tab.icon} size={24}/><span>{tab.label}</span></button>)}</div><div className="rail-bottom"><button title="How to play" onClick={()=>setHelp(true)}><Icon name="help"/></button><button title="Settings" onClick={()=>{setRename(town.name);setSettings(true)}}><Icon name="crown"/></button><button title="Return to main menu" onClick={onExit}><Icon name="exit"/></button></div></nav>
   <header className="realm-topbar"><div className="realm-brand"><strong>PERIS</strong><span>THE AGE OF AMBITION</span></div><div className="resource-strip">{RESOURCES.map(k=><div key={k} className={`resource ${resources[k]>=town.capacity?'full':''}`} title={`${resources[k]} / ${town.capacity} capacity`}><Icon name={k} size={23}/><div><strong>{resources[k].toLocaleString()}</strong><small>{k==='wood'?'TIMBER':k.toUpperCase()} <b>+{town[`${k}_rate`]}/m</b></small></div></div>)}</div><div className="ruler"><span className="live-dot"/><div><strong>{player.display_name}</strong><small>{engine.mode==='online'?'SHARED WORLD':'SOLO CAMPAIGN'} · {player.prestige} prestige</small></div></div></header>
   <main className={`realm-content ${view==='world'?'world-content':''}`}>
    {view==='world'?<><aside className="campaign-sidebar"><div className="province-title"><span className="eyebrow">CAMPAIGN · CHAPTER I</span><h1>The lost province</h1><p>Six rebel hosts. One land to reclaim.</p></div><div className="sidebar-section"><label className="field-label">REBEL HOSTS <span>{world.progress.filter(p=>p.defeated>0).length} / 6</span></label><div className="camp-list">{world.camps.map(c=>{const cleared=world.progress.some(p=>p.camp_id===c.id&&p.defeated>0);return <button key={c.id} className={selectedCamp?.id===c.id?'selected':''} onClick={()=>setSelection({kind:'camp',id:c.id})}><span className={`camp-tier ${cleared?'cleared':''}`}>{cleared?<Icon name="check" size={14}/>:c.tier}</span><span>{c.name}<small>{c.terrain} · {soldierTotal(c)} soldiers</small></span><Icon name="arrow" size={13}/></button>})}</div></div><div className="sidebar-section objectives"><label className="field-label">YOUR OBJECTIVES</label>{QUESTS.map(q=>{const claimed=world.claims.some(c=>c.quest_id===q.id),completed=player[q.stat]>=q.target;return <div className={`objective ${claimed?'complete':''}`} key={q.id}><div><Icon name={claimed?'check':'flag'} size={15}/><strong>{q.title}</strong></div><p>{q.description}</p><div className="objective-bottom"><small>{Math.min(q.target,player[q.stat])} / {q.target}</small>{claimed?<span>Claimed</span>:completed?<button onClick={()=>dispatch({type:'claim',questId:q.id},'Objective reward collected')} disabled={busy}>Claim reward →</button>:<span>+{q.reward.gold} gold</span>}</div></div>})}</div></aside>
    <section className="world-stage"><div className="world-toolbar"><div><strong>The province of Peris</strong><span>Discover. March. Conquer.</span></div><div><span className="map-legend"><i/> Your legion <i/> Rebel hosts</span><button className={moveMode?'selected':''} onClick={()=>setMoveMode(m=>!m)}><Icon name="flag" size={16}/>{moveMode?'Cancel march':'March'}</button></div></div><div className="world-map-wrap"><GameCanvas state={{world,playerId:engine.playerId,mode:'world',selection,selectedIds:[],moveMode}} actions={{selectMap:setSelection,moveArmy:(x,y)=>{setMoveMode(false);dispatch({type:'move',x,y},'Marching orders issued')},selectUnits:()=>{},order:()=>{},pause:()=>{},rally:()=>{}}}/>
      {moveMode&&<div className="map-command-hint"><Icon name="flag"/>Click a destination for your legion.</div>}
      {selection&&<aside className="map-inspector"><button className="inspector-close" aria-label="Close map details" onClick={()=>setSelection(null)}>×</button>
       {selectedCamp&&<><span className="eyebrow">REBEL ENCAMPMENT · TIER {selectedCamp.tier}</span><h2>{selectedCamp.name}</h2><p>{selectedCamp.description}</p><div className="camp-force"><span><Icon name="army" size={16}/>{selectedCamp.infantry} infantry</span><span>{selectedCamp.archers} archers</span><span>{selectedCamp.cavalry} cavalry</span></div><div className="camp-tags"><span>{selectedCamp.terrain}</span><span>{selectedCamp.tier===1?'Recruit commander':selectedCamp.tier>=4?'Expert commander':'Veteran commander'}</span></div><label className="field-label">VICTORY SPOILS</label><Cost cost={lootFor(selectedCamp.tier)} compact/><button className="button gold" disabled={busy||moving||!!(cooldown&&Date.parse(cooldown.available_at)>now)||soldierTotal(army)===0} onClick={()=>dispatch({type:'raid',campId:selectedCamp.id},`Marching to ${selectedCamp.name}`)}>{cooldown&&Date.parse(cooldown.available_at)>now?`Regroups in ${clock((Date.parse(cooldown.available_at)-now)/1000)}`:moving?'Legion is marching':'March and engage'}<Icon name="arrow" size={16}/></button><small>Your army travels to the camp, then enters deployment.</small></>}
       {selectedTown&&<><span className="eyebrow">{selectedTown.owner_id===engine.playerId?'YOUR SETTLEMENT':'RIVAL SETTLEMENT'}</span><h2>{selectedTown.name}</h2><p>Ruled by {playerName(world.players,selectedTown.owner_id)}.</p>{selectedTown.owner_id===engine.playerId?<button className="button gold" onClick={()=>navigate('settlement')}>Enter the city<Icon name="arrow" size={16}/></button>:<button className="button outline" disabled={busy||outgoing.length>0} onClick={()=>dispatch({type:'challenge',ownerId:selectedTown.owner_id},'Battle invitation sent')}>Invite to a live duel</button>}</>}
       {selectedArmy&&<><span className="eyebrow">{selectedArmy.owner_id===engine.playerId?'YOUR LEGION':'RIVAL LEGION'}</span><h2>{selectedArmy.name}</h2><p>{soldierTotal(selectedArmy)} soldiers under {playerName(world.players,selectedArmy.owner_id)}.</p>{selectedArmy.owner_id===engine.playerId?<><button className="button gold" onClick={()=>{setMoveMode(true);setSelection(null)}}>Give marching orders<Icon name="arrow" size={16}/></button><button className="button outline" onClick={()=>navigate('army')}>Manage troops</button></>:<button className="button outline" disabled={busy||outgoing.length>0} onClick={()=>dispatch({type:'challenge',ownerId:selectedArmy.owner_id},'Battle invitation sent')}>Invite to a live duel</button>}</>}
      </aside>}
     </div><footer className="march-status"><div className="legion-badge"><Icon name="army" size={23}/><div><strong>{army.name}</strong><small>{army.infantry} infantry · {army.archers} archers · {army.cavalry} cavalry</small></div></div><div className="march-state"><span className={moving?'marching-dot':'resting-dot'}/><span>{moving?`Marching · ${clock((Date.parse(army.arrival_at)-now)/1000)} to arrival`:dist(armyPosition(army,now),{x:town.x+40,y:town.y+30})<90?'At the keep · ready for orders':'On the field · ready for orders'}</span></div><button onClick={()=>dispatch({type:'move',x:town.x+40,y:town.y+30},'The legion returns home')} disabled={busy}>Return home</button></footer></section></>:
     view==='settlement'?<SettlementView world={world} playerId={engine.playerId} run={dispatch} busy={busy} now={now}/>:view==='army'?<ArmyView world={world} playerId={engine.playerId} run={dispatch} busy={busy} now={now}/>:<Chronicle world={world} playerId={engine.playerId} onReport={setReport}/>}
   </main>
   <footer className="realm-footer"><span>PERIS · EMPIRE PROTOTYPE V0.6</span><span>{engine.mode==='online'?`${world.players.length} rulers in the province`:'Solo progress saved automatically'}<button onClick={()=>setHelp(true)}>How to play</button></span></footer>
  </div>}
  {notice&&<div className={`toast ${notice.error?'error':''}`} role="status"><Icon name={notice.error?'shield':'check'}/>{notice.text}<button aria-label="Dismiss notification" onClick={()=>setNotice(null)}>×</button></div>}
  {engine instanceof OnlineEngine&&engine.error&&<div className="connection-warning">Connection interrupted. Your last world state is displayed; retrying…</div>}
  {!active&&incoming.length>0&&<div className="challenge-banner"><Icon name="army"/><span>{playerName(world.players,incoming[0].attacker_owner_id)} challenges your legion. <small>Survivors return home; casualties are permanent.</small></span><button className="button gold" disabled={busy} onClick={()=>dispatch({type:'respond',id:incoming[0].id,accept:true})}>Accept battle</button><button className="button outline" disabled={busy} onClick={()=>dispatch({type:'respond',id:incoming[0].id,accept:false})}>Decline</button></div>}
  {!active&&outgoing.length>0&&<div className="outgoing-challenge">Battle invitation pending · {clock((Date.parse(outgoing[0].expires_at)-now)/1000)}</div>}
  {report?.result&&<div className="modal-backdrop"><section className="modal result-modal" role="dialog" aria-modal="true" aria-label="Battle result"><ResultBody result={report.result} won={report.winner_owner_id===engine.playerId} side={mySide(report,engine.playerId)} enemyName={report.enemy_name}/><button className="button gold" onClick={()=>{setReport(null);if(engine.mode==='practice')onExit();else navigate('world')}}>{engine.mode==='practice'?'Return to main menu':'Return to the province'}<Icon name="arrow" size={16}/></button></section></div>}
  {help&&<Modal title="Your orders, General" onClose={()=>setHelp(false)}><p>Develop your city, raise a legion, and reclaim the six rebel camps. The final host guards the fallen capital.</p><ol className="help-steps"><li><strong>Build your economy.</strong> Open City, select a building, and begin an upgrade. Income continues while you are away.</li><li><strong>Raise troops.</strong> Open Army to train infantry, archers, and cavalry. Recruitment works at the keep, in batches.</li><li><strong>March to battle.</strong> Select a camp and choose March and engage. Your legion enters deployment on arrival.</li><li><strong>Command the field.</strong> Left click or drag to select. Shift adds units. Right click moves or attacks. Right-drag sets a line's width and facing.</li><li><strong>Win through position.</strong> Protect archers, brace infantry in Guard, charge cavalry into flanks and rear. Forests reduce ranged damage; ridges favour archers; river shallows slow troops.</li></ol><div className="help-shortcuts"><span>A · select all</span><span>1–9 · select unit</span><span>H · halt</span><span>G · guard</span><span>R · rally</span><span>F · focus selection</span><span>Space · solo pause</span><span>Arrows · camera</span></div><p className="muted">Multiplayer duels require both players to accept and finish deployment. Live combat advances while a participant is connected. Campaign movement, income, and queues are resolved when you return.</p></Modal>}
  {settings&&<Modal title="Your realm" onClose={()=>setSettings(false)}><label className="field-label" htmlFor="settlement-name">SETTLEMENT NAME</label><input id="settlement-name" value={rename} onChange={e=>setRename(e.target.value)} maxLength={32}/><button className="button gold" disabled={busy} onClick={()=>{dispatch({type:'rename',name:rename},'Settlement renamed');setSettings(false)}}>Save settlement name</button><div className="rule"/><button className="settings-action" onClick={()=>{setAudio(!sound);setSound(!sound)}}><Icon name={sound?'sound':'mute'}/><span>Command sounds</span><b>{sound?'On':'Off'}</b></button>{engine.mode==='solo'&&<button className="settings-action" onClick={exportSave}><Icon name="download"/><span>Export campaign save</span></button>}<p className="muted">Solo campaigns are stored in this browser. Multiplayer uses your existing anonymous account. Returning to the menu keeps the account and realm.</p><button className="button outline" onClick={onExit}>Return to main menu</button></Modal>}
 </>
}
